// Mock data for Creative Workspace
// This will be replaced with API calls in production

import { Ticket, Brand, TeamMember, TicketStatus, Asset } from "@/types/creative"

// =============================================================================
// TEAM MEMBERS
// =============================================================================

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Sarah Chen",
    email: "sarah.chen@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=sarah.chen",
    role: "creative",
    skills: ["UI Design", "Branding", "Illustration"],
    currentLoad: 80,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-2",
    name: "Mike Johnson",
    email: "mike.johnson@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=mike.johnson",
    role: "creative",
    skills: ["Web Design", "Motion Graphics"],
    currentLoad: 60,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-3",
    name: "Emily Davis",
    email: "emily.davis@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=emily.davis",
    role: "creative",
    skills: ["Print Design", "Packaging"],
    currentLoad: 40,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-4",
    name: "Alex Kim",
    email: "alex.kim@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=alex.kim",
    role: "creative",
    skills: ["Social Media", "Email Design"],
    currentLoad: 50,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-5",
    name: "Jordan Lee",
    email: "jordan.lee@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=jordan.lee",
    role: "team_leader",
    skills: ["Project Management", "Art Direction"],
    currentLoad: 70,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-6",
    name: "Taylor Smith",
    email: "taylor.smith@creationrights.com",
    avatar: "https://i.pravatar.cc/150?u=taylor.smith",
    role: "qa",
    skills: ["Quality Assurance", "Brand Compliance"],
    currentLoad: 55,
    maxCapacity: 100,
    isAvailable: true,
  },
]

// =============================================================================
// BRANDS
// =============================================================================

export const mockBrands: Brand[] = [
  {
    id: "brand-1",
    name: "Acme Corporation",
    logoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    description: "A leading provider of innovative solutions for modern businesses.",
    targetAudience: "B2B Enterprise, Tech-savvy decision makers",
    mission: "To empower businesses with cutting-edge technology",
    vision: "A world where technology simplifies business",
    values: ["Innovation", "Reliability", "Customer Focus"],
    personality: ["Professional", "Trustworthy", "Forward-thinking"],
    colors: [
      { id: "c1", name: "Primary Blue", hex: "#3b82f6", type: "primary" },
      { id: "c2", name: "Dark Navy", hex: "#1e3a5f", type: "secondary" },
      { id: "c3", name: "Accent Orange", hex: "#f97316", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Inter", type: "primary", usage: "Headlines and body text" },
      { id: "f2", name: "Roboto Mono", type: "secondary", usage: "Code and technical content" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-11-20"),
  },
  {
    id: "brand-2",
    name: "TechStart Inc",
    logoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    description: "Startup accelerator helping founders build the next big thing.",
    targetAudience: "Startup founders, VCs, Tech entrepreneurs",
    mission: "To fuel innovation and entrepreneurship",
    vision: "Every great idea deserves a chance to succeed",
    values: ["Boldness", "Community", "Growth"],
    personality: ["Energetic", "Supportive", "Ambitious"],
    colors: [
      { id: "c1", name: "Electric Purple", hex: "#8b5cf6", type: "primary" },
      { id: "c2", name: "Deep Violet", hex: "#4c1d95", type: "secondary" },
    ],
    fonts: [
      { id: "f1", name: "Space Grotesk", type: "primary", usage: "All text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-11-18"),
  },
  {
    id: "brand-3",
    name: "NatureFresh Foods",
    logoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    description: "Organic and sustainable food products for health-conscious consumers.",
    targetAudience: "Health-conscious families, Millennials, Eco-friendly consumers",
    mission: "To nourish people and planet with wholesome food",
    vision: "A healthier world through sustainable nutrition",
    values: ["Sustainability", "Health", "Transparency"],
    personality: ["Natural", "Caring", "Authentic"],
    colors: [
      { id: "c1", name: "Forest Green", hex: "#22c55e", type: "primary" },
      { id: "c2", name: "Earth Brown", hex: "#78350f", type: "secondary" },
      { id: "c3", name: "Sunny Yellow", hex: "#fbbf24", type: "accent" },
      { id: "c4", name: "Cream", hex: "#fef3c7", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Nunito", type: "primary", usage: "Headlines" },
      { id: "f2", name: "Open Sans", type: "secondary", usage: "Body text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-11-15"),
  },
  {
    id: "brand-4",
    name: "Urban Style Co",
    logoUrl: "https://placehold.co/100x100/171717/white?text=U",
    description: "Contemporary streetwear and lifestyle brand for urban youth.",
    targetAudience: "Gen Z, Urban youth, Fashion-forward individuals",
    mission: "To define street culture through bold fashion",
    vision: "Where street meets style",
    values: ["Authenticity", "Self-expression", "Community"],
    personality: ["Bold", "Edgy", "Youthful"],
    colors: [
      { id: "c1", name: "Midnight Black", hex: "#171717", type: "primary" },
      { id: "c2", name: "Neon Pink", hex: "#ec4899", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Bebas Neue", type: "primary", usage: "Headlines" },
      { id: "f2", name: "DM Sans", type: "secondary", usage: "Body text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2025-04-05"),
    updatedAt: new Date("2025-11-22"),
  },
]

// =============================================================================
// TICKETS
// =============================================================================

export const mockTickets: Ticket[] = [
  // SUBMITTED
  {
    id: "ticket-1",
    title: "Trade Show Booth Graphics",
    designType: "trade_show",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "Q1 Events",
    targetAudience: "Tech conference attendees, potential investors",
    description: "We need a complete booth design for the upcoming TechCrunch Disrupt conference. The booth is 10x10 feet. We need backdrop graphics, standee designs, and handout materials.",
    status: "submitted",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2025-12-20"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-2",
    title: "Holiday Email Campaign",
    designType: "email",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    projectTag: "Holiday 2024",
    targetAudience: "Existing customers, Newsletter subscribers",
    description: "Design a series of 3 holiday-themed email templates promoting our seasonal products. Should feel festive but align with our natural, organic brand identity.",
    status: "submitted",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2025-12-15"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2025-12-02"),
    updatedAt: new Date("2025-12-02"),
  },
  {
    id: "ticket-3",
    title: "New Product Packaging",
    designType: "packaging",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    projectTag: "Product Launch",
    targetAudience: "Health-conscious shoppers",
    description: "Design packaging for our new line of organic protein bars. Need front and back panel designs for 3 flavors: Chocolate, Vanilla, and Berry.",
    status: "submitted",
    priority: "urgent",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2025-12-18"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2025-12-03"),
    updatedAt: new Date("2025-12-03"),
  },

  // ASSESSMENT
  {
    id: "ticket-4",
    title: "Annual Report Design",
    designType: "pdf_ebook",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Corporate",
    targetAudience: "Shareholders, Board members, Investors",
    description: "Design our 2024 Annual Report. Approximately 40 pages including financials, letter from CEO, and key highlights. Need to convey professionalism and growth.",
    status: "assessment",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: 24,
    trackedTime: 0,
    dueDate: new Date("2025-12-30"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-28"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-5",
    title: "Instagram Story Templates",
    designType: "social_media",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    projectTag: "Social 2024",
    targetAudience: "Gen Z, Instagram users",
    description: "Create a set of 10 Instagram story templates for product launches, sales announcements, and behind-the-scenes content. Should be bold and eye-catching.",
    status: "assessment",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: 8,
    trackedTime: 0,
    dueDate: new Date("2025-12-12"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2025-11-29"),
    updatedAt: new Date("2025-12-02"),
  },

  // ASSIGNED
  {
    id: "ticket-6",
    title: "Business Card Redesign",
    designType: "business_card",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Brand Refresh",
    targetAudience: "Business contacts, clients",
    description: "Redesign business cards to match our updated brand guidelines. Need front and back design with new logo placement. Standard size.",
    status: "assigned",
    priority: "low",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://i.pravatar.cc/150?u=sarah.chen",
    estimatedHours: 4,
    trackedTime: 0,
    dueDate: new Date("2025-12-10"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-7",
    title: "Landing Page Hero Section",
    designType: "web_design",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "Website Redesign",
    targetAudience: "Startup founders seeking funding",
    description: "Design a new hero section for our main landing page. Should communicate 'accelerate your startup' and include space for headline, subheadline, CTA button, and a visual element.",
    status: "assigned",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    assigneeAvatar: "https://i.pravatar.cc/150?u=mike.johnson",
    estimatedHours: 8,
    trackedTime: 0,
    dueDate: new Date("2025-12-08"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2025-11-26"),
    updatedAt: new Date("2025-12-01"),
  },

  // PRODUCTION
  {
    id: "ticket-8",
    title: "Social Media Pack Q1",
    designType: "social_media",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "Social Q1",
    targetAudience: "LinkedIn and Twitter followers",
    description: "Create a pack of 20 social media graphics for Q1 content calendar. Mix of quote graphics, event announcements, and tip posts.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Initial Concepts",
        url: "/versions/v1.zip",
        uploadedAt: new Date("2025-12-01"),
        uploadedBy: "tm-4",
        notes: "First round of 5 template concepts"
      }
    ],
    comments: [
      {
        id: "c1",
        content: "Looking good so far! Can we try a version with darker backgrounds?",
        authorId: "client-4",
        authorName: "Alex Rivera",
        createdAt: new Date("2025-12-02"),
      }
    ],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    assigneeAvatar: "https://i.pravatar.cc/150?u=alex.kim",
    estimatedHours: 16,
    trackedTime: 8,
    dueDate: new Date("2025-12-15"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-12-02"),
  },
  {
    id: "ticket-9",
    title: "Product Catalog Design",
    designType: "pdf_ebook",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    projectTag: "Spring Collection",
    targetAudience: "Retailers, wholesale buyers",
    description: "Design a 24-page product catalog for our Spring 2025 collection. Should showcase products in a lifestyle context with pricing and ordering information.",
    status: "production",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Layout Draft",
        url: "/versions/catalog-v1.pdf",
        uploadedAt: new Date("2025-11-28"),
        uploadedBy: "tm-3",
        notes: "Initial layout for review"
      },
      {
        id: "v2",
        number: 2,
        name: "Revised Layout",
        url: "/versions/catalog-v2.pdf",
        uploadedAt: new Date("2025-12-01"),
        uploadedBy: "tm-3",
        notes: "Updated based on feedback"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    assigneeAvatar: "https://i.pravatar.cc/150?u=emily.davis",
    estimatedHours: 20,
    trackedTime: 14,
    dueDate: new Date("2025-12-10"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-10",
    title: "Email Newsletter Template",
    designType: "email",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Marketing",
    targetAudience: "B2B prospects and customers",
    description: "Design a reusable email newsletter template for monthly company updates. Should include header, featured article section, news grid, and footer.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Initial Design",
        url: "/versions/newsletter-v1.html",
        uploadedAt: new Date("2025-11-30"),
        uploadedBy: "tm-4",
        notes: "First version of template"
      }
    ],
    comments: [],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    assigneeAvatar: "https://i.pravatar.cc/150?u=alex.kim",
    estimatedHours: 6,
    trackedTime: 4,
    dueDate: new Date("2025-12-06"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-22"),
    updatedAt: new Date("2025-11-30"),
  },
  {
    id: "ticket-11",
    title: "Homepage Banner Redesign",
    designType: "web_design",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Website",
    targetAudience: "Website visitors",
    description: "Redesign the main homepage banner to highlight our new enterprise solution. Should be impactful and drive clicks to the product page.",
    status: "production",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://i.pravatar.cc/150?u=sarah.chen",
    estimatedHours: 6,
    trackedTime: 3,
    dueDate: new Date("2025-12-05"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-28"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-12",
    title: "Presentation Template",
    designType: "presentation",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "Sales",
    targetAudience: "Potential startup clients",
    description: "Create a master presentation template with 15+ slide layouts for sales pitches. Include title, content, comparison, quote, and closing slides.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    assigneeAvatar: "https://i.pravatar.cc/150?u=mike.johnson",
    estimatedHours: 12,
    trackedTime: 6,
    dueDate: new Date("2025-12-12"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2025-12-01"),
  },

  // QA REVIEW
  {
    id: "ticket-13",
    title: "Promotional Flyer Design",
    designType: "poster_flyer",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    projectTag: "Retail",
    targetAudience: "In-store shoppers",
    description: "Design an A4 promotional flyer for our Black Friday sale. Should highlight key discounts and drive urgency.",
    status: "qa_review",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Design",
        url: "/versions/flyer-final.pdf",
        uploadedAt: new Date("2025-12-01"),
        uploadedBy: "tm-3",
        notes: "Ready for QA review"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    assigneeAvatar: "https://i.pravatar.cc/150?u=emily.davis",
    estimatedHours: 4,
    trackedTime: 4,
    dueDate: new Date("2025-12-04"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "ticket-14",
    title: "Logo Refresh",
    designType: "logo_branding",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    projectTag: "Brand Refresh",
    targetAudience: "All brand touchpoints",
    description: "Modernize our existing logo while maintaining brand recognition. Need primary logo, secondary mark, and favicon versions.",
    status: "qa_review",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Concepts",
        url: "/versions/logo-concepts.pdf",
        uploadedAt: new Date("2025-11-25"),
        uploadedBy: "tm-1",
        notes: "3 concept directions"
      },
      {
        id: "v2",
        number: 2,
        name: "Refined Direction",
        url: "/versions/logo-v2.pdf",
        uploadedAt: new Date("2025-11-28"),
        uploadedBy: "tm-1",
        notes: "Refined based on feedback"
      },
      {
        id: "v3",
        number: 3,
        name: "Final Versions",
        url: "/versions/logo-final.zip",
        uploadedAt: new Date("2025-12-02"),
        uploadedBy: "tm-1",
        notes: "All logo variants in various formats"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://i.pravatar.cc/150?u=sarah.chen",
    estimatedHours: 16,
    trackedTime: 18,
    dueDate: new Date("2025-12-05"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2025-11-10"),
    updatedAt: new Date("2025-12-02"),
  },

  // DELIVERED
  {
    id: "ticket-15",
    title: "Product Launch Graphics",
    designType: "digital_marketing",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Product Launch",
    targetAudience: "Enterprise IT decision makers",
    description: "Create digital marketing graphics for new product launch including web banners, social graphics, and email header.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Deliverables",
        url: "/versions/launch-graphics.zip",
        uploadedAt: new Date("2025-11-28"),
        uploadedBy: "tm-2",
        notes: "All final assets"
      }
    ],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    assigneeAvatar: "https://i.pravatar.cc/150?u=mike.johnson",
    estimatedHours: 12,
    trackedTime: 10,
    dueDate: new Date("2025-11-30"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2025-11-28"),
  },
  {
    id: "ticket-16",
    title: "Event Invitation Design",
    designType: "email",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "Events",
    targetAudience: "Startup community, past attendees",
    description: "Design email invitation for our annual Demo Day event. Should create excitement and drive RSVPs.",
    status: "delivered",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Design",
        url: "/versions/invite-final.html",
        uploadedAt: new Date("2025-11-25"),
        uploadedBy: "tm-4",
        notes: "Approved and delivered"
      }
    ],
    comments: [],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    assigneeAvatar: "https://i.pravatar.cc/150?u=alex.kim",
    estimatedHours: 4,
    trackedTime: 3,
    dueDate: new Date("2025-11-26"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2025-11-18"),
    updatedAt: new Date("2025-11-25"),
  },
  {
    id: "ticket-17",
    title: "Recipe Cards Series",
    designType: "print_merch",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    projectTag: "Content Marketing",
    targetAudience: "Home cooks, health enthusiasts",
    description: "Design a series of 12 recipe cards featuring our products. Print-ready format with photos, ingredients, and instructions.",
    status: "delivered",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Cards",
        url: "/versions/recipe-cards.zip",
        uploadedAt: new Date("2025-11-22"),
        uploadedBy: "tm-3",
        notes: "All 12 cards, print-ready"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    assigneeAvatar: "https://i.pravatar.cc/150?u=emily.davis",
    estimatedHours: 8,
    trackedTime: 7,
    dueDate: new Date("2025-11-23"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2025-11-10"),
    updatedAt: new Date("2025-11-22"),
  },
  {
    id: "ticket-18",
    title: "Sticker Pack Design",
    designType: "sticker_keychain",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    projectTag: "Merch",
    targetAudience: "Young customers, brand fans",
    description: "Design a pack of 8 die-cut stickers featuring our brand elements, slogans, and iconic imagery.",
    status: "delivered",
    priority: "low",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Stickers",
        url: "/versions/stickers.zip",
        uploadedAt: new Date("2025-11-20"),
        uploadedBy: "tm-1",
        notes: "Ready for production"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://i.pravatar.cc/150?u=sarah.chen",
    estimatedHours: 6,
    trackedTime: 5,
    dueDate: new Date("2025-11-21"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2025-11-12"),
    updatedAt: new Date("2025-11-20"),
  },
  {
    id: "ticket-19",
    title: "Conference Presentation",
    designType: "presentation",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    projectTag: "Events",
    targetAudience: "Conference attendees, industry peers",
    description: "Design a keynote presentation for our CEO's talk at the annual industry conference. 30 slides, professional and impactful.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Presentation",
        url: "/versions/keynote-final.pptx",
        uploadedAt: new Date("2025-11-18"),
        uploadedBy: "tm-2",
        notes: "Approved by CEO"
      }
    ],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    assigneeAvatar: "https://i.pravatar.cc/150?u=mike.johnson",
    estimatedHours: 16,
    trackedTime: 14,
    dueDate: new Date("2025-11-19"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2025-11-18"),
  },
  {
    id: "ticket-20",
    title: "Mobile App UI Mockups",
    designType: "ux_ui",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    projectTag: "App Development",
    targetAudience: "Mobile app users",
    description: "Design high-fidelity UI mockups for our new mobile app. 10 key screens including onboarding, dashboard, and profile.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Mockups",
        url: "/versions/app-mockups.fig",
        uploadedAt: new Date("2025-11-15"),
        uploadedBy: "tm-1",
        notes: "Figma file with all screens"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://i.pravatar.cc/150?u=sarah.chen",
    estimatedHours: 24,
    trackedTime: 22,
    dueDate: new Date("2025-11-16"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2025-10-28"),
    updatedAt: new Date("2025-11-15"),
  },
]

// =============================================================================
// ASSETS
// =============================================================================

export const mockAssets: Asset[] = [
  {
    id: "asset-1",
    name: "Homepage Banner - Holiday Sale.png",
    description: "Main banner for the holiday sale campaign",
    thumbnailUrl: "https://picsum.photos/seed/asset1/400/300",
    fileUrl: "/assets/banner-holiday.png",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/png",
    fileSize: 2400000,
    dimensions: { width: 1920, height: 600 },
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-15",
    ticketTitle: "Product Launch Graphics",
    designType: "digital_marketing",
    tags: ["banner", "homepage", "sale", "holiday"],
    uploadedById: "tm-2",
    uploadedByName: "Mike Johnson",
    createdAt: new Date("2025-11-28"),
    updatedAt: new Date("2025-11-28"),
    promptHistory: {
      messages: [
        {
          id: "msg-1",
          role: "user",
          content: "Create a vibrant holiday sale banner for our homepage. It should feature festive colors, include 'Holiday Sale' text prominently, and have a modern, professional look that matches our brand.",
          timestamp: new Date("2025-11-28T10:00:00"),
        },
        {
          id: "msg-2",
          role: "assistant",
          content: "I'll create a holiday sale banner with festive colors and professional design. Let me generate a few options for you.",
          timestamp: new Date("2025-11-28T10:00:15"),
          model: "DALL-E 3",
        },
        {
          id: "msg-3",
          role: "user",
          content: "Can you make it more winter-themed? Add snowflakes and use a blue and white color scheme instead.",
          timestamp: new Date("2025-11-28T10:05:00"),
        },
        {
          id: "msg-4",
          role: "assistant",
          content: "Perfect! I've updated the banner with a winter theme, snowflakes, and a blue and white color palette. The design maintains the professional look while adding the festive winter elements you requested.",
          timestamp: new Date("2025-11-28T10:05:20"),
          model: "DALL-E 3",
          parameters: {
            style: "professional",
            aspect_ratio: "16:5",
            color_scheme: "blue and white",
            elements: ["snowflakes", "holiday text", "winter theme"],
          },
        },
      ],
      aiTool: "DALL-E",
      modelVersion: "3",
      generationDate: new Date("2025-11-28T10:05:20"),
    },
    copyrightCheckStatus: "completed",
    copyrightCheckProgress: 100,
    copyrightCheckData: {
      similarityScore: 12,
      matchedSources: [],
      riskBreakdown: {
        copyrightRisk: 5,
        trademarkRisk: 2,
        overallRisk: 8,
        riskLevel: "low",
      },
      recommendations: [
        "Asset passed copyright check with low similarity score.",
        "No matches found in copyright databases.",
        "Safe to use in production.",
      ],
      checkedAt: new Date("2025-11-28T10:10:00"),
      checkDuration: 4500,
    },
    approvalStatus: "approved",
    approvedBy: "admin-1",
    approvedAt: new Date("2025-11-28T10:15:00"),
  },
  {
    id: "asset-2",
    name: "Social Media Pack - Q1 Templates.zip",
    description: "Complete social media template pack for Q1 content",
    thumbnailUrl: "https://picsum.photos/seed/asset2/400/300",
    fileUrl: "/assets/social-pack-q1.zip",
    fileType: "archive",
    contentType: "original",
    mimeType: "application/zip",
    fileSize: 15600000,
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    ticketId: "ticket-8",
    ticketTitle: "Social Media Pack Q1",
    designType: "social_media",
    tags: ["social", "templates", "instagram", "linkedin"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-12-02"),
    updatedAt: new Date("2025-12-02"),
  },
  {
    id: "asset-3",
    name: "Annual Report 2024.pdf",
    description: "Complete annual report document",
    thumbnailUrl: "https://picsum.photos/seed/asset3/400/300",
    fileUrl: "/assets/annual-report-2024.pdf",
    fileType: "pdf",
    contentType: "original",
    mimeType: "application/pdf",
    fileSize: 8900000,
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    designType: "pdf_ebook",
    tags: ["annual report", "corporate", "2024"],
    uploadedById: "tm-3",
    uploadedByName: "Emily Davis",
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-11-20"),
  },
  {
    id: "asset-4",
    name: "Logo - Primary.svg",
    description: "Primary logo in SVG format",
    thumbnailUrl: "https://picsum.photos/seed/asset4/400/300",
    fileUrl: "/assets/logo-primary.svg",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/svg+xml",
    fileSize: 45000,
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    ticketId: "ticket-14",
    ticketTitle: "Logo Refresh",
    designType: "logo_branding",
    tags: ["logo", "branding", "svg", "primary"],
    uploadedById: "tm-1",
    uploadedByName: "Sarah Chen",
    createdAt: new Date("2025-12-02"),
    updatedAt: new Date("2025-12-02"),
    promptHistory: {
      messages: [
        {
          id: "msg-logo-1",
          role: "user",
          content: "Design a modern, minimalist logo for 'Urban Style Co'. It should be sleek, contemporary, and work well in both light and dark backgrounds. The logo should represent urban fashion and style.",
          timestamp: new Date("2025-12-02T09:30:00"),
        },
        {
          id: "msg-logo-2",
          role: "assistant",
          content: "I've created several logo concepts for Urban Style Co. Here are three options with different styles - one geometric, one typographic, and one icon-based. Which direction would you like to explore further?",
          timestamp: new Date("2025-12-02T09:30:25"),
          model: "Midjourney",
        },
        {
          id: "msg-logo-3",
          role: "user",
          content: "I like the geometric one, but can you make it more abstract and use a monochrome color scheme? Also, ensure it's scalable for small sizes.",
          timestamp: new Date("2025-12-02T09:45:00"),
        },
        {
          id: "msg-logo-4",
          role: "assistant",
          content: "Perfect! I've refined the geometric logo with a more abstract design, using a monochrome palette. The design is optimized for scalability and will work well at any size from business cards to billboards.",
          timestamp: new Date("2025-12-02T09:45:30"),
          model: "Midjourney",
          parameters: {
            style: "geometric abstract",
            color_mode: "monochrome",
            format: "SVG",
            scalability: "optimized",
            version: "v6",
          },
        },
      ],
      aiTool: "Midjourney",
      modelVersion: "6.0",
      generationDate: new Date("2025-12-02T09:45:30"),
    },
    copyrightCheckStatus: "completed",
    copyrightCheckProgress: 100,
    copyrightCheckData: {
      similarityScore: 45,
      matchedSources: [
        {
          id: "match-1",
          title: "Abstract Geometric Logo Design",
          url: "https://example.com/match1",
          similarity: 45,
          type: "image",
          source: "Shutterstock",
        },
        {
          id: "match-2",
          title: "Modern Minimalist Logo",
          url: "https://example.com/match2",
          similarity: 32,
          type: "image",
          source: "Getty Images",
        },
      ],
      riskBreakdown: {
        copyrightRisk: 65,
        trademarkRisk: 30,
        overallRisk: 55,
        riskLevel: "high",
      },
      recommendations: [
        "Similarity score of 45% exceeds the 30% threshold.",
        "Found 2 potential matches in copyright databases.",
        "Requires admin review before approval.",
        "Consider modifying design elements to reduce similarity.",
      ],
      checkedAt: new Date("2025-12-02T10:00:00"),
      checkDuration: 6200,
    },
    approvalStatus: "pending",
  },
  {
    id: "asset-5",
    name: "Email Newsletter Template.html",
    description: "Responsive email template for monthly newsletters",
    thumbnailUrl: "https://picsum.photos/seed/asset5/400/300",
    fileUrl: "/assets/newsletter-template.html",
    fileType: "document",
    contentType: "original",
    mimeType: "text/html",
    fileSize: 125000,
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-10",
    ticketTitle: "Email Newsletter Template",
    designType: "email",
    tags: ["email", "newsletter", "template", "responsive"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-11-30"),
    updatedAt: new Date("2025-11-30"),
  },
  {
    id: "asset-6",
    name: "Product Catalog Spring 2025.pdf",
    description: "Complete product catalog for Spring 2025 collection",
    thumbnailUrl: "https://picsum.photos/seed/asset6/400/300",
    fileUrl: "/assets/catalog-spring-2025.pdf",
    fileType: "pdf",
    contentType: "original",
    mimeType: "application/pdf",
    fileSize: 24500000,
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    ticketId: "ticket-9",
    ticketTitle: "Product Catalog Design",
    designType: "pdf_ebook",
    tags: ["catalog", "products", "spring", "2025"],
    uploadedById: "tm-3",
    uploadedByName: "Emily Davis",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "asset-7",
    name: "Promotional Flyer - Black Friday.pdf",
    description: "A4 promotional flyer for Black Friday sale",
    thumbnailUrl: "https://picsum.photos/seed/asset7/400/300",
    fileUrl: "/assets/flyer-black-friday.pdf",
    fileType: "pdf",
    contentType: "original",
    mimeType: "application/pdf",
    fileSize: 3200000,
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    ticketId: "ticket-13",
    ticketTitle: "Promotional Flyer Design",
    designType: "poster_flyer",
    tags: ["flyer", "black friday", "sale", "print"],
    uploadedById: "tm-3",
    uploadedByName: "Emily Davis",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "asset-8",
    name: "Demo Day Invitation.html",
    description: "Email invitation design for annual Demo Day event",
    thumbnailUrl: "https://picsum.photos/seed/asset8/400/300",
    fileUrl: "/assets/demo-day-invite.html",
    fileType: "document",
    contentType: "original",
    mimeType: "text/html",
    fileSize: 98000,
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    ticketId: "ticket-16",
    ticketTitle: "Event Invitation Design",
    designType: "email",
    tags: ["email", "invitation", "event", "demo day"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2025-11-25"),
  },
  {
    id: "asset-9",
    name: "Recipe Cards Collection.zip",
    description: "12 print-ready recipe cards featuring products",
    thumbnailUrl: "https://picsum.photos/seed/asset9/400/300",
    fileUrl: "/assets/recipe-cards.zip",
    fileType: "archive",
    contentType: "original",
    mimeType: "application/zip",
    fileSize: 18700000,
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    ticketId: "ticket-17",
    ticketTitle: "Recipe Cards Series",
    designType: "print_merch",
    tags: ["recipe", "cards", "print", "food"],
    uploadedById: "tm-3",
    uploadedByName: "Emily Davis",
    createdAt: new Date("2025-11-22"),
    updatedAt: new Date("2025-11-22"),
  },
  {
    id: "asset-10",
    name: "Sticker Pack Designs.ai",
    description: "8 die-cut sticker designs in Illustrator format",
    thumbnailUrl: "https://picsum.photos/seed/asset10/400/300",
    fileUrl: "/assets/sticker-pack.ai",
    fileType: "document",
    contentType: "original",
    mimeType: "application/illustrator",
    fileSize: 5400000,
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    ticketId: "ticket-18",
    ticketTitle: "Sticker Pack Design",
    designType: "sticker_keychain",
    tags: ["stickers", "merch", "illustrator"],
    uploadedById: "tm-1",
    uploadedByName: "Sarah Chen",
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-11-20"),
  },
  {
    id: "asset-11",
    name: "Conference Keynote.pptx",
    description: "30-slide keynote presentation for industry conference",
    thumbnailUrl: "https://picsum.photos/seed/asset11/400/300",
    fileUrl: "/assets/keynote-conference.pptx",
    fileType: "document",
    contentType: "original",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    fileSize: 12300000,
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-19",
    ticketTitle: "Conference Presentation",
    designType: "presentation",
    tags: ["presentation", "keynote", "conference"],
    uploadedById: "tm-2",
    uploadedByName: "Mike Johnson",
    createdAt: new Date("2025-11-18"),
    updatedAt: new Date("2025-11-18"),
  },
  {
    id: "asset-12",
    name: "Mobile App UI Mockups.fig",
    description: "High-fidelity UI mockups for mobile app",
    thumbnailUrl: "https://picsum.photos/seed/asset12/400/300",
    fileUrl: "/assets/app-mockups.fig",
    fileType: "document",
    contentType: "original",
    mimeType: "application/figma",
    fileSize: 8900000,
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    ticketId: "ticket-20",
    ticketTitle: "Mobile App UI Mockups",
    designType: "ux_ui",
    tags: ["ui", "ux", "mobile", "figma", "mockups"],
    uploadedById: "tm-1",
    uploadedByName: "Sarah Chen",
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2025-11-15"),
  },
  {
    id: "asset-13",
    name: "Instagram Story Templates.psd",
    description: "10 editable Instagram story templates",
    thumbnailUrl: "https://picsum.photos/seed/asset13/400/300",
    fileUrl: "/assets/ig-stories.psd",
    fileType: "image",
    contentType: "original",
    mimeType: "image/vnd.adobe.photoshop",
    fileSize: 45600000,
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    designType: "social_media",
    tags: ["instagram", "stories", "templates", "photoshop"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-11-10"),
    updatedAt: new Date("2025-11-10"),
  },
  {
    id: "asset-14",
    name: "Business Cards - Final.pdf",
    description: "Print-ready business card designs",
    thumbnailUrl: "https://picsum.photos/seed/asset14/400/300",
    fileUrl: "/assets/business-cards.pdf",
    fileType: "pdf",
    contentType: "original",
    mimeType: "application/pdf",
    fileSize: 1200000,
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-6",
    ticketTitle: "Business Card Redesign",
    designType: "business_card",
    tags: ["business cards", "print", "corporate"],
    uploadedById: "tm-1",
    uploadedByName: "Sarah Chen",
    createdAt: new Date("2025-12-03"),
    updatedAt: new Date("2025-12-03"),
  },
  {
    id: "asset-15",
    name: "Landing Page Hero.png",
    description: "Hero section graphic for landing page",
    thumbnailUrl: "https://picsum.photos/seed/asset15/400/300",
    fileUrl: "/assets/hero-landing.png",
    fileType: "image",
    contentType: "original",
    mimeType: "image/png",
    fileSize: 3400000,
    dimensions: { width: 1440, height: 800 },
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    ticketId: "ticket-7",
    ticketTitle: "Landing Page Hero Section",
    designType: "web_design",
    tags: ["hero", "landing page", "web", "header"],
    uploadedById: "tm-2",
    uploadedByName: "Mike Johnson",
    createdAt: new Date("2025-12-02"),
    updatedAt: new Date("2025-12-02"),
  },
  {
    id: "asset-16",
    name: "Product Showcase Banner.png",
    description: "AI-generated product showcase banner with modern gradient design",
    thumbnailUrl: "https://picsum.photos/seed/asset16/400/300",
    fileUrl: "/assets/product-showcase-banner.png",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/png",
    fileSize: 2800000,
    dimensions: { width: 1920, height: 1080 },
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandLogoUrl: "https://placehold.co/100x100/8b5cf6/white?text=T",
    brandColor: "#8b5cf6",
    ticketId: "ticket-21",
    ticketTitle: "Product Showcase Graphics",
    designType: "digital_marketing",
    tags: ["banner", "product", "showcase", "gradient"],
    uploadedById: "tm-2",
    uploadedByName: "Mike Johnson",
    createdAt: new Date("2025-12-04"),
    updatedAt: new Date("2025-12-04"),
    promptHistory: {
      messages: [
        {
          id: "msg-prod-1",
          role: "user",
          content: "Create a modern product showcase banner with a sleek gradient background. It should have a tech-forward aesthetic with clean lines and vibrant colors that match our brand. Include space for product imagery and compelling call-to-action text.",
          timestamp: new Date("2025-12-04T14:30:00"),
        },
        {
          id: "msg-prod-2",
          role: "assistant",
          content: "I've created a modern product showcase banner with a gradient background and tech-forward design. The layout includes designated areas for product imagery and call-to-action text.",
          timestamp: new Date("2025-12-04T14:30:25"),
          model: "Midjourney",
          parameters: {
            style: "modern tech",
            aspect_ratio: "16:9",
            color_scheme: "gradient purple to blue",
            elements: ["product showcase", "gradient background", "clean lines"],
            version: "v6",
          },
        },
      ],
      aiTool: "Midjourney",
      modelVersion: "6.0",
      generationDate: new Date("2025-12-04T14:30:25"),
    },
  },
  {
    id: "asset-17",
    name: "Social Media Post - Product Launch.jpg",
    description: "AI-generated Instagram post for product launch announcement",
    thumbnailUrl: "https://picsum.photos/seed/asset17/400/300",
    fileUrl: "/assets/social-product-launch.jpg",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/jpeg",
    fileSize: 1850000,
    dimensions: { width: 1080, height: 1080 },
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-22",
    ticketTitle: "Social Media Product Launch",
    designType: "social_media",
    tags: ["instagram", "product launch", "social", "square"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-12-05"),
    updatedAt: new Date("2025-12-05"),
    promptHistory: {
      messages: [
        {
          id: "msg-social-1",
          role: "user",
          content: "Design an Instagram square post for a product launch. Make it eye-catching with bold typography, vibrant colors, and include 'New Product Launch' text. The design should be modern and engaging for social media.",
          timestamp: new Date("2025-12-05T09:15:00"),
        },
        {
          id: "msg-social-2",
          role: "assistant",
          content: "I've created an eye-catching Instagram post with bold typography and vibrant colors. The design is optimized for social media engagement with clear 'New Product Launch' messaging.",
          timestamp: new Date("2025-12-05T09:15:20"),
          model: "DALL-E 3",
          parameters: {
            style: "modern social media",
            aspect_ratio: "1:1",
            format: "square",
            color_scheme: "vibrant",
            typography: "bold",
            elements: ["product launch", "social media", "engaging design"],
          },
        },
      ],
      aiTool: "DALL-E",
      modelVersion: "3",
      generationDate: new Date("2025-12-05T09:15:20"),
    },
  },
  {
    id: "asset-18",
    name: "Email Header - Newsletter.png",
    description: "AI-generated email header design for monthly newsletter",
    thumbnailUrl: "https://picsum.photos/seed/asset18/400/300",
    fileUrl: "/assets/email-newsletter-header.png",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/png",
    fileSize: 950000,
    dimensions: { width: 600, height: 200 },
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandLogoUrl: "https://placehold.co/100x100/22c55e/white?text=N",
    brandColor: "#22c55e",
    ticketId: "ticket-23",
    ticketTitle: "Newsletter Email Header",
    designType: "email",
    tags: ["email", "newsletter", "header", "monthly"],
    uploadedById: "tm-4",
    uploadedByName: "Alex Kim",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
    promptHistory: {
      messages: [
        {
          id: "msg-email-1",
          role: "user",
          content: "Create an email header for our monthly newsletter. It should be clean, professional, and include natural/organic elements since we're a food brand. Use our brand colors and make it email-friendly (600px width).",
          timestamp: new Date("2025-12-01T11:20:00"),
        },
        {
          id: "msg-email-2",
          role: "assistant",
          content: "I've created a clean, professional email header with natural elements that reflect your food brand. The design uses your brand colors and is optimized for email clients at 600px width.",
          timestamp: new Date("2025-12-01T11:20:30"),
          model: "Stable Diffusion",
          parameters: {
            style: "clean professional",
            width: 600,
            height: 200,
            color_scheme: "brand colors with natural elements",
            elements: ["newsletter header", "organic", "email-friendly"],
            version: "XL",
          },
        },
      ],
      aiTool: "Stable Diffusion",
      modelVersion: "XL",
      generationDate: new Date("2025-12-01T11:20:30"),
    },
  },
  {
    id: "asset-19",
    name: "Web Banner - Summer Campaign.png",
    description: "AI-generated web banner for summer marketing campaign",
    thumbnailUrl: "https://picsum.photos/seed/asset19/400/300",
    fileUrl: "/assets/summer-campaign-banner.png",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/png",
    fileSize: 3200000,
    dimensions: { width: 1920, height: 600 },
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandLogoUrl: "https://placehold.co/100x100/171717/white?text=U",
    brandColor: "#171717",
    ticketId: "ticket-24",
    ticketTitle: "Summer Campaign Banner",
    designType: "digital_marketing",
    tags: ["banner", "summer", "campaign", "web"],
    uploadedById: "tm-2",
    uploadedByName: "Mike Johnson",
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2025-11-25"),
    promptHistory: {
      messages: [
        {
          id: "msg-summer-1",
          role: "user",
          content: "Design a vibrant summer campaign web banner. Include bright, warm colors like oranges, yellows, and blues. The design should feel energetic and seasonal, perfect for a summer sale campaign. Make it 1920x600 pixels.",
          timestamp: new Date("2025-11-25T13:45:00"),
        },
        {
          id: "msg-summer-2",
          role: "assistant",
          content: "I've created a vibrant summer campaign banner with warm, energetic colors. The design captures the seasonal feel and is optimized for web display at 1920x600 pixels.",
          timestamp: new Date("2025-11-25T13:45:25"),
          model: "DALL-E 3",
          parameters: {
            style: "vibrant energetic",
            aspect_ratio: "16:5",
            color_scheme: "warm oranges, yellows, blues",
            elements: ["summer", "campaign", "seasonal", "energetic"],
          },
        },
      ],
      aiTool: "DALL-E",
      modelVersion: "3",
      generationDate: new Date("2025-11-25T13:45:25"),
    },
  },
  {
    id: "asset-20",
    name: "Icon Set - Brand Elements.svg",
    description: "AI-generated icon set featuring brand-specific design elements",
    thumbnailUrl: "https://picsum.photos/seed/asset20/400/300",
    fileUrl: "/assets/brand-icons.svg",
    fileType: "image",
    contentType: "ai_generated",
    mimeType: "image/svg+xml",
    fileSize: 125000,
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandLogoUrl: "https://placehold.co/100x100/3b82f6/white?text=A",
    brandColor: "#3b82f6",
    ticketId: "ticket-25",
    ticketTitle: "Brand Icon Set",
    designType: "logo_branding",
    tags: ["icons", "branding", "svg", "set"],
    uploadedById: "tm-1",
    uploadedByName: "Sarah Chen",
    createdAt: new Date("2025-11-30"),
    updatedAt: new Date("2025-11-30"),
    promptHistory: {
      messages: [
        {
          id: "msg-icon-1",
          role: "user",
          content: "Generate a cohesive set of brand icons in SVG format. The icons should be minimalist, modern, and match our corporate brand aesthetic. Include icons for: products, services, about, and contact. All icons should share a consistent style and be scalable.",
          timestamp: new Date("2025-11-30T15:00:00"),
        },
        {
          id: "msg-icon-2",
          role: "assistant",
          content: "I've created a cohesive set of minimalist, modern brand icons in SVG format. All icons share a consistent style and are optimized for scalability across different sizes.",
          timestamp: new Date("2025-11-30T15:00:35"),
          model: "Midjourney",
          parameters: {
            style: "minimalist modern",
            format: "SVG",
            color_mode: "monochrome",
            scalability: "optimized",
            icon_count: 4,
            version: "v6",
          },
        },
      ],
      aiTool: "Midjourney",
      modelVersion: "6.0",
      generationDate: new Date("2025-11-30T15:00:35"),
    },
  },
]

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getTicketsByStatus(status: TicketStatus): Ticket[] {
  return mockTickets.filter((ticket) => ticket.status === status)
}

export function getTicketById(id: string): Ticket | undefined {
  return mockTickets.find((ticket) => ticket.id === id)
}

export function getBrandById(id: string): Brand | undefined {
  return mockBrands.find((brand) => brand.id === id)
}

export function getTeamMemberById(id: string): TeamMember | undefined {
  return mockTeamMembers.find((member) => member.id === id)
}

export function getTicketCountByStatus(): Record<TicketStatus, number> {
  return {
    submitted: getTicketsByStatus("submitted").length,
    assessment: getTicketsByStatus("assessment").length,
    assigned: getTicketsByStatus("assigned").length,
    production: getTicketsByStatus("production").length,
    qa_review: getTicketsByStatus("qa_review").length,
    delivered: getTicketsByStatus("delivered").length,
  }
}

export function getAssetById(id: string): Asset | undefined {
  return mockAssets.find((asset) => asset.id === id)
}

export function getAssetsByBrand(brandId: string): Asset[] {
  return mockAssets.filter((asset) => asset.brandId === brandId)
}

export function getAssetsByTicket(ticketId: string): Asset[] {
  return mockAssets.filter((asset) => asset.ticketId === ticketId)
}

