// Mock data for Creative Workspace
// This will be replaced with API calls in production

import { Ticket, Brand, TeamMember, TicketStatus } from "@/types/creative"

// =============================================================================
// TEAM MEMBERS
// =============================================================================

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Sarah Chen",
    email: "sarah.chen@creationrights.com",
    avatar: undefined,
    role: "creative",
    skills: ["UI Design", "Branding", "Illustration"],
    currentLoad: 80,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-2",
    name: "Mike Johnson",
    email: "mike.johnson@creationrights.com",
    avatar: undefined,
    role: "creative",
    skills: ["Web Design", "Motion Graphics"],
    currentLoad: 60,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-3",
    name: "Emily Davis",
    email: "emily.davis@creationrights.com",
    avatar: undefined,
    role: "creative",
    skills: ["Print Design", "Packaging"],
    currentLoad: 40,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-4",
    name: "Alex Kim",
    email: "alex.kim@creationrights.com",
    avatar: undefined,
    role: "creative",
    skills: ["Social Media", "Email Design"],
    currentLoad: 50,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-5",
    name: "Jordan Lee",
    email: "jordan.lee@creationrights.com",
    avatar: undefined,
    role: "team_leader",
    skills: ["Project Management", "Art Direction"],
    currentLoad: 70,
    maxCapacity: 100,
    isAvailable: true,
  },
  {
    id: "tm-6",
    name: "Taylor Smith",
    email: "taylor.smith@creationrights.com",
    avatar: undefined,
    role: "qa",
    skills: ["Quality Assurance", "Brand Compliance"],
    currentLoad: 55,
    maxCapacity: 100,
    isAvailable: true,
  },
]

// =============================================================================
// BRANDS
// =============================================================================

export const mockBrands: Brand[] = [
  {
    id: "brand-1",
    name: "Acme Corporation",
    description: "A leading provider of innovative solutions for modern businesses.",
    targetAudience: "B2B Enterprise, Tech-savvy decision makers",
    mission: "To empower businesses with cutting-edge technology",
    vision: "A world where technology simplifies business",
    values: ["Innovation", "Reliability", "Customer Focus"],
    personality: ["Professional", "Trustworthy", "Forward-thinking"],
    colors: [
      { id: "c1", name: "Primary Blue", hex: "#3b82f6", type: "primary" },
      { id: "c2", name: "Dark Navy", hex: "#1e3a5f", type: "secondary" },
      { id: "c3", name: "Accent Orange", hex: "#f97316", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Inter", type: "primary", usage: "Headlines and body text" },
      { id: "f2", name: "Roboto Mono", type: "secondary", usage: "Code and technical content" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "brand-2",
    name: "TechStart Inc",
    description: "Startup accelerator helping founders build the next big thing.",
    targetAudience: "Startup founders, VCs, Tech entrepreneurs",
    mission: "To fuel innovation and entrepreneurship",
    vision: "Every great idea deserves a chance to succeed",
    values: ["Boldness", "Community", "Growth"],
    personality: ["Energetic", "Supportive", "Ambitious"],
    colors: [
      { id: "c1", name: "Electric Purple", hex: "#8b5cf6", type: "primary" },
      { id: "c2", name: "Deep Violet", hex: "#4c1d95", type: "secondary" },
      { id: "c3", name: "Lime Green", hex: "#84cc16", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Space Grotesk", type: "primary", usage: "All text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "brand-3",
    name: "NatureFresh Foods",
    description: "Organic and sustainable food products for health-conscious consumers.",
    targetAudience: "Health-conscious families, Millennials, Eco-friendly consumers",
    mission: "To nourish people and planet with wholesome food",
    vision: "A healthier world through sustainable nutrition",
    values: ["Sustainability", "Health", "Transparency"],
    personality: ["Natural", "Caring", "Authentic"],
    colors: [
      { id: "c1", name: "Forest Green", hex: "#22c55e", type: "primary" },
      { id: "c2", name: "Earth Brown", hex: "#78350f", type: "secondary" },
      { id: "c3", name: "Sunny Yellow", hex: "#fbbf24", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Nunito", type: "primary", usage: "Headlines" },
      { id: "f2", name: "Open Sans", type: "secondary", usage: "Body text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "brand-4",
    name: "Urban Style Co",
    description: "Contemporary streetwear and lifestyle brand for urban youth.",
    targetAudience: "Gen Z, Urban youth, Fashion-forward individuals",
    mission: "To define street culture through bold fashion",
    vision: "Where street meets style",
    values: ["Authenticity", "Self-expression", "Community"],
    personality: ["Bold", "Edgy", "Youthful"],
    colors: [
      { id: "c1", name: "Midnight Black", hex: "#171717", type: "primary" },
      { id: "c2", name: "Pure White", hex: "#fafafa", type: "secondary" },
      { id: "c3", name: "Neon Pink", hex: "#ec4899", type: "accent" },
    ],
    fonts: [
      { id: "f1", name: "Bebas Neue", type: "primary", usage: "Headlines" },
      { id: "f2", name: "DM Sans", type: "secondary", usage: "Body text" },
    ],
    logos: [],
    referenceImages: [],
    inspirations: [],
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-11-22"),
  },
]

// =============================================================================
// TICKETS
// =============================================================================

export const mockTickets: Ticket[] = [
  // SUBMITTED
  {
    id: "ticket-1",
    title: "Trade Show Booth Graphics",
    designType: "trade_show",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "Q1 Events",
    targetAudience: "Tech conference attendees, potential investors",
    description: "We need a complete booth design for the upcoming TechCrunch Disrupt conference. The booth is 10x10 feet. We need backdrop graphics, standee designs, and handout materials.",
    status: "submitted",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2024-12-20"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-2",
    title: "Holiday Email Campaign",
    designType: "email",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandColor: "#22c55e",
    projectTag: "Holiday 2024",
    targetAudience: "Existing customers, Newsletter subscribers",
    description: "Design a series of 3 holiday-themed email templates promoting our seasonal products. Should feel festive but align with our natural, organic brand identity.",
    status: "submitted",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2024-12-15"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2024-12-02"),
    updatedAt: new Date("2024-12-02"),
  },
  {
    id: "ticket-3",
    title: "New Product Packaging",
    designType: "packaging",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandColor: "#22c55e",
    projectTag: "Product Launch",
    targetAudience: "Health-conscious shoppers",
    description: "Design packaging for our new line of organic protein bars. Need front and back panel designs for 3 flavors: Chocolate, Vanilla, and Berry.",
    status: "submitted",
    priority: "urgent",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: undefined,
    trackedTime: 0,
    dueDate: new Date("2024-12-18"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2024-12-03"),
    updatedAt: new Date("2024-12-03"),
  },

  // ASSESSMENT
  {
    id: "ticket-4",
    title: "Annual Report Design",
    designType: "pdf_ebook",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Corporate",
    targetAudience: "Shareholders, Board members, Investors",
    description: "Design our 2024 Annual Report. Approximately 40 pages including financials, letter from CEO, and key highlights. Need to convey professionalism and growth.",
    status: "assessment",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: 24,
    trackedTime: 0,
    dueDate: new Date("2024-12-30"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-28"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-5",
    title: "Instagram Story Templates",
    designType: "social_media",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandColor: "#171717",
    projectTag: "Social 2024",
    targetAudience: "Gen Z, Instagram users",
    description: "Create a set of 10 Instagram story templates for product launches, sales announcements, and behind-the-scenes content. Should be bold and eye-catching.",
    status: "assessment",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: undefined,
    estimatedHours: 8,
    trackedTime: 0,
    dueDate: new Date("2024-12-12"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2024-11-29"),
    updatedAt: new Date("2024-12-02"),
  },

  // ASSIGNED
  {
    id: "ticket-6",
    title: "Business Card Redesign",
    designType: "business_card",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Brand Refresh",
    targetAudience: "Business contacts, clients",
    description: "Redesign business cards to match our updated brand guidelines. Need front and back design with new logo placement. Standard size.",
    status: "assigned",
    priority: "low",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    estimatedHours: 4,
    trackedTime: 0,
    dueDate: new Date("2024-12-10"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-7",
    title: "Landing Page Hero Section",
    designType: "web_design",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "Website Redesign",
    targetAudience: "Startup founders seeking funding",
    description: "Design a new hero section for our main landing page. Should communicate 'accelerate your startup' and include space for headline, subheadline, CTA button, and a visual element.",
    status: "assigned",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    estimatedHours: 8,
    trackedTime: 0,
    dueDate: new Date("2024-12-08"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2024-11-26"),
    updatedAt: new Date("2024-12-01"),
  },

  // PRODUCTION
  {
    id: "ticket-8",
    title: "Social Media Pack Q1",
    designType: "social_media",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "Social Q1",
    targetAudience: "LinkedIn and Twitter followers",
    description: "Create a pack of 20 social media graphics for Q1 content calendar. Mix of quote graphics, event announcements, and tip posts.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Initial Concepts",
        url: "/versions/v1.zip",
        uploadedAt: new Date("2024-12-01"),
        uploadedBy: "tm-4",
        notes: "First round of 5 template concepts"
      }
    ],
    comments: [
      {
        id: "c1",
        content: "Looking good so far! Can we try a version with darker backgrounds?",
        authorId: "client-4",
        authorName: "Alex Rivera",
        createdAt: new Date("2024-12-02"),
      }
    ],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    estimatedHours: 16,
    trackedTime: 8,
    dueDate: new Date("2024-12-15"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-12-02"),
  },
  {
    id: "ticket-9",
    title: "Product Catalog Design",
    designType: "pdf_ebook",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandColor: "#171717",
    projectTag: "Spring Collection",
    targetAudience: "Retailers, wholesale buyers",
    description: "Design a 24-page product catalog for our Spring 2025 collection. Should showcase products in a lifestyle context with pricing and ordering information.",
    status: "production",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Layout Draft",
        url: "/versions/catalog-v1.pdf",
        uploadedAt: new Date("2024-11-28"),
        uploadedBy: "tm-3",
        notes: "Initial layout for review"
      },
      {
        id: "v2",
        number: 2,
        name: "Revised Layout",
        url: "/versions/catalog-v2.pdf",
        uploadedAt: new Date("2024-12-01"),
        uploadedBy: "tm-3",
        notes: "Updated based on feedback"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    estimatedHours: 20,
    trackedTime: 14,
    dueDate: new Date("2024-12-10"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-10",
    title: "Email Newsletter Template",
    designType: "email",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Marketing",
    targetAudience: "B2B prospects and customers",
    description: "Design a reusable email newsletter template for monthly company updates. Should include header, featured article section, news grid, and footer.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Initial Design",
        url: "/versions/newsletter-v1.html",
        uploadedAt: new Date("2024-11-30"),
        uploadedBy: "tm-4",
        notes: "First version of template"
      }
    ],
    comments: [],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    estimatedHours: 6,
    trackedTime: 4,
    dueDate: new Date("2024-12-06"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-22"),
    updatedAt: new Date("2024-11-30"),
  },
  {
    id: "ticket-11",
    title: "Homepage Banner Redesign",
    designType: "web_design",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Website",
    targetAudience: "Website visitors",
    description: "Redesign the main homepage banner to highlight our new enterprise solution. Should be impactful and drive clicks to the product page.",
    status: "production",
    priority: "high",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    estimatedHours: 6,
    trackedTime: 3,
    dueDate: new Date("2024-12-05"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-28"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-12",
    title: "Presentation Template",
    designType: "presentation",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "Sales",
    targetAudience: "Potential startup clients",
    description: "Create a master presentation template with 15+ slide layouts for sales pitches. Include title, content, comparison, quote, and closing slides.",
    status: "production",
    priority: "medium",
    attachments: [],
    versions: [],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    estimatedHours: 12,
    trackedTime: 6,
    dueDate: new Date("2024-12-12"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-12-01"),
  },

  // QA REVIEW
  {
    id: "ticket-13",
    title: "Promotional Flyer Design",
    designType: "poster_flyer",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandColor: "#22c55e",
    projectTag: "Retail",
    targetAudience: "In-store shoppers",
    description: "Design an A4 promotional flyer for our Black Friday sale. Should highlight key discounts and drive urgency.",
    status: "qa_review",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Design",
        url: "/versions/flyer-final.pdf",
        uploadedAt: new Date("2024-12-01"),
        uploadedBy: "tm-3",
        notes: "Ready for QA review"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    estimatedHours: 4,
    trackedTime: 4,
    dueDate: new Date("2024-12-04"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ticket-14",
    title: "Logo Refresh",
    designType: "logo_branding",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandColor: "#171717",
    projectTag: "Brand Refresh",
    targetAudience: "All brand touchpoints",
    description: "Modernize our existing logo while maintaining brand recognition. Need primary logo, secondary mark, and favicon versions.",
    status: "qa_review",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Concepts",
        url: "/versions/logo-concepts.pdf",
        uploadedAt: new Date("2024-11-25"),
        uploadedBy: "tm-1",
        notes: "3 concept directions"
      },
      {
        id: "v2",
        number: 2,
        name: "Refined Direction",
        url: "/versions/logo-v2.pdf",
        uploadedAt: new Date("2024-11-28"),
        uploadedBy: "tm-1",
        notes: "Refined based on feedback"
      },
      {
        id: "v3",
        number: 3,
        name: "Final Versions",
        url: "/versions/logo-final.zip",
        uploadedAt: new Date("2024-12-02"),
        uploadedBy: "tm-1",
        notes: "All logo variants in various formats"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    estimatedHours: 16,
    trackedTime: 18,
    dueDate: new Date("2024-12-05"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-12-02"),
  },

  // DELIVERED
  {
    id: "ticket-15",
    title: "Product Launch Graphics",
    designType: "digital_marketing",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Product Launch",
    targetAudience: "Enterprise IT decision makers",
    description: "Create digital marketing graphics for new product launch including web banners, social graphics, and email header.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Deliverables",
        url: "/versions/launch-graphics.zip",
        uploadedAt: new Date("2024-11-28"),
        uploadedBy: "tm-2",
        notes: "All final assets"
      }
    ],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    estimatedHours: 12,
    trackedTime: 10,
    dueDate: new Date("2024-11-30"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-28"),
  },
  {
    id: "ticket-16",
    title: "Event Invitation Design",
    designType: "email",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "Events",
    targetAudience: "Startup community, past attendees",
    description: "Design email invitation for our annual Demo Day event. Should create excitement and drive RSVPs.",
    status: "delivered",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Design",
        url: "/versions/invite-final.html",
        uploadedAt: new Date("2024-11-25"),
        uploadedBy: "tm-4",
        notes: "Approved and delivered"
      }
    ],
    comments: [],
    assigneeId: "tm-4",
    assigneeName: "Alex Kim",
    estimatedHours: 4,
    trackedTime: 3,
    dueDate: new Date("2024-11-26"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-25"),
  },
  {
    id: "ticket-17",
    title: "Recipe Cards Series",
    designType: "print_merch",
    brandId: "brand-3",
    brandName: "NatureFresh Foods",
    brandColor: "#22c55e",
    projectTag: "Content Marketing",
    targetAudience: "Home cooks, health enthusiasts",
    description: "Design a series of 12 recipe cards featuring our products. Print-ready format with photos, ingredients, and instructions.",
    status: "delivered",
    priority: "medium",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Cards",
        url: "/versions/recipe-cards.zip",
        uploadedAt: new Date("2024-11-22"),
        uploadedBy: "tm-3",
        notes: "All 12 cards, print-ready"
      }
    ],
    comments: [],
    assigneeId: "tm-3",
    assigneeName: "Emily Davis",
    estimatedHours: 8,
    trackedTime: 7,
    dueDate: new Date("2024-11-23"),
    createdBy: "client-2",
    createdByName: "Maria Garcia",
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "ticket-18",
    title: "Sticker Pack Design",
    designType: "sticker_keychain",
    brandId: "brand-4",
    brandName: "Urban Style Co",
    brandColor: "#171717",
    projectTag: "Merch",
    targetAudience: "Young customers, brand fans",
    description: "Design a pack of 8 die-cut stickers featuring our brand elements, slogans, and iconic imagery.",
    status: "delivered",
    priority: "low",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Stickers",
        url: "/versions/stickers.zip",
        uploadedAt: new Date("2024-11-20"),
        uploadedBy: "tm-1",
        notes: "Ready for production"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    estimatedHours: 6,
    trackedTime: 5,
    dueDate: new Date("2024-11-21"),
    createdBy: "client-3",
    createdByName: "Chris Taylor",
    createdAt: new Date("2024-11-12"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "ticket-19",
    title: "Conference Presentation",
    designType: "presentation",
    brandId: "brand-1",
    brandName: "Acme Corporation",
    brandColor: "#3b82f6",
    projectTag: "Events",
    targetAudience: "Conference attendees, industry peers",
    description: "Design a keynote presentation for our CEO's talk at the annual industry conference. 30 slides, professional and impactful.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Presentation",
        url: "/versions/keynote-final.pptx",
        uploadedAt: new Date("2024-11-18"),
        uploadedBy: "tm-2",
        notes: "Approved by CEO"
      }
    ],
    comments: [],
    assigneeId: "tm-2",
    assigneeName: "Mike Johnson",
    estimatedHours: 16,
    trackedTime: 14,
    dueDate: new Date("2024-11-19"),
    createdBy: "client-1",
    createdByName: "John Smith",
    createdAt: new Date("2024-11-05"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "ticket-20",
    title: "Mobile App UI Mockups",
    designType: "ux_ui",
    brandId: "brand-2",
    brandName: "TechStart Inc",
    brandColor: "#8b5cf6",
    projectTag: "App Development",
    targetAudience: "Mobile app users",
    description: "Design high-fidelity UI mockups for our new mobile app. 10 key screens including onboarding, dashboard, and profile.",
    status: "delivered",
    priority: "high",
    attachments: [],
    versions: [
      {
        id: "v1",
        number: 1,
        name: "Final Mockups",
        url: "/versions/app-mockups.fig",
        uploadedAt: new Date("2024-11-15"),
        uploadedBy: "tm-1",
        notes: "Figma file with all screens"
      }
    ],
    comments: [],
    assigneeId: "tm-1",
    assigneeName: "Sarah Chen",
    estimatedHours: 24,
    trackedTime: 22,
    dueDate: new Date("2024-11-16"),
    createdBy: "client-4",
    createdByName: "Alex Rivera",
    createdAt: new Date("2024-10-28"),
    updatedAt: new Date("2024-11-15"),
  },
]

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getTicketsByStatus(status: TicketStatus): Ticket[] {
  return mockTickets.filter((ticket) => ticket.status === status)
}

export function getTicketById(id: string): Ticket | undefined {
  return mockTickets.find((ticket) => ticket.id === id)
}

export function getBrandById(id: string): Brand | undefined {
  return mockBrands.find((brand) => brand.id === id)
}

export function getTeamMemberById(id: string): TeamMember | undefined {
  return mockTeamMembers.find((member) => member.id === id)
}

export function getTicketCountByStatus(): Record<TicketStatus, number> {
  return {
    submitted: getTicketsByStatus("submitted").length,
    assessment: getTicketsByStatus("assessment").length,
    assigned: getTicketsByStatus("assigned").length,
    production: getTicketsByStatus("production").length,
    qa_review: getTicketsByStatus("qa_review").length,
    delivered: getTicketsByStatus("delivered").length,
  }
}

