import type { EditableField } from "@/types/bulk-edit"

export const BULK_EDIT_CATEGORIES = {
  basic: "Basic Information",
  brand: "Brand & Design",
  files: "File Properties",
  copyright: "Copyright & Legal",
  accessibility: "Accessibility",
  seo: "SEO",
  talent: "Talent Rights (NILP)",
  ai: "AI Generation",
  approval: "Approval & Status",
  version: "Version Management",
  performance: "Performance",
  security: "Security",
}

export const EDITABLE_FIELDS: EditableField[] = [
  // BASIC INFORMATION
  {
    id: "name",
    label: "Asset Name",
    type: "text",
    category: "basic",
    path: "name",
    editable: true,
    validation: { required: true },
  },
  {
    id: "description",
    label: "Description",
    type: "textarea",
    category: "basic",
    path: "description",
    editable: true,
    versionEditable: true,
  },
  {
    id: "tags",
    label: "Tags",
    type: "tags",
    category: "basic",
    path: "tags",
    editable: true,
    versionEditable: false,
    inheritedFromParent: true,
  },
  {
    id: "intendedUses",
    label: "Intended Uses",
    type: "badge-multiselect",
    category: "basic",
    path: "intendedUses",
    editable: true,
    versionEditable: false,
    inheritedFromParent: true,
    badgeColor: "blue",
    options: [
      { value: "Advertising/Campaigns", label: "Advertising/Campaigns" },
      { value: "Editorial", label: "Editorial" },
      { value: "Internal", label: "Internal" },
      { value: "Social Media", label: "Social Media" },
      { value: "Print", label: "Print" },
      { value: "Web", label: "Web" },
      { value: "Video", label: "Video" },
    ],
  },
  
  // BRAND & DESIGN
  {
    id: "brandId",
    label: "Brand",
    type: "searchable-select",
    category: "brand",
    path: "brandId",
    editable: true,
    versionEditable: false,
    inheritedFromParent: true,
    searchable: true,
    options: [], // Populated dynamically from brands context
  },
  {
    id: "designType",
    label: "Design Type",
    type: "badge-multiselect",
    category: "brand",
    path: "designType",
    editable: true,
    versionEditable: false,
    inheritedFromParent: true,
    badgeColor: "purple",
    options: [
      { value: "digital_marketing", label: "Digital Marketing" },
      { value: "social_media", label: "Social Media" },
      { value: "ecommerce", label: "E-commerce" },
      { value: "email", label: "Email" },
      { value: "logo_branding", label: "Logo & Branding" },
      { value: "pdf_ebook", label: "PDF/eBook" },
      { value: "presentation", label: "Presentation" },
      { value: "web_design", label: "Web Design" },
      { value: "ux_ui", label: "UX/UI" },
      { value: "print_merch", label: "Print Merch" },
      { value: "packaging", label: "Packaging" },
      { value: "poster_flyer", label: "Poster/Flyer" },
      { value: "trade_show", label: "Trade Show" },
      { value: "business_card", label: "Business Card" },
      { value: "sticker_keychain", label: "Sticker/Keychain" },
      { value: "custom", label: "Custom" },
    ],
  },
  {
    id: "brandName",
    label: "Brand Name",
    type: "text",
    category: "brand",
    path: "brandName",
    editable: true,
  },
  
  // FILE PROPERTIES
  {
    id: "fileType",
    label: "File Type",
    type: "select",
    category: "files",
    path: "fileType",
    editable: true,
    options: [
      { value: "image", label: "Image" },
      { value: "video", label: "Video" },
      { value: "pdf", label: "PDF" },
      { value: "document", label: "Document" },
      { value: "archive", label: "Archive" },
      { value: "other", label: "Other" },
    ],
  },
  {
    id: "contentType",
    label: "Content Type",
    type: "select",
    category: "files",
    path: "contentType",
    editable: true,
    options: [
      { value: "original", label: "Original" },
      { value: "ai_generated", label: "AI Generated" },
    ],
  },
  {
    id: "mimeType",
    label: "MIME Type",
    type: "text",
    category: "files",
    path: "mimeType",
    editable: true,
  },
  {
    id: "fileSize",
    label: "File Size",
    type: "number",
    category: "files",
    path: "fileSize",
    editable: false,
    unit: "MB",
    helpText: "Read-only: Calculated from file",
  },
  
  // COPYRIGHT & LEGAL
  {
    id: "copyrightStatus",
    label: "Copyright Check Status",
    type: "select",
    category: "copyright",
    path: "copyrightCheckStatus",
    editable: true,
    options: [
      { value: "pending", label: "Pending" },
      { value: "checking", label: "Checking" },
      { value: "completed", label: "Completed" },
      { value: "failed", label: "Failed" },
    ],
  },
  {
    id: "copyrightSimilarity",
    label: "Similarity Score",
    type: "number",
    category: "copyright",
    path: "copyrightCheckData.similarityScore",
    editable: false,
    helpText: "Read-only: Updated by copyright check",
  },
  {
    id: "copyrightRiskLevel",
    label: "Risk Level",
    type: "select",
    category: "copyright",
    path: "copyrightCheckData.riskBreakdown.overall",
    editable: false,
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
      { value: "critical", label: "Critical" },
    ],
  },
  
  // ACCESSIBILITY
  {
    id: "accessibilityScore",
    label: "Accessibility Score",
    type: "number",
    category: "accessibility",
    path: "reviewData.accessibility.data.score",
    editable: false,
    helpText: "0-100 WCAG compliance score",
  },
  {
    id: "wcagLevel",
    label: "WCAG Level",
    type: "select",
    category: "accessibility",
    path: "reviewData.accessibility.data.wcagLevel",
    editable: true,
    options: [
      { value: "none", label: "None" },
      { value: "A", label: "A" },
      { value: "AA", label: "AA" },
      { value: "AAA", label: "AAA" },
    ],
  },
  {
    id: "altTextQuality",
    label: "Alt Text Quality",
    type: "select",
    category: "accessibility",
    path: "reviewData.accessibility.data.altText.quality",
    editable: true,
    options: [
      { value: "good", label: "Good" },
      { value: "fair", label: "Fair" },
      { value: "poor", label: "Poor" },
      { value: "missing", label: "Missing" },
    ],
  },
  {
    id: "altTextPresent",
    label: "Alt Text Present",
    type: "boolean",
    category: "accessibility",
    path: "reviewData.accessibility.data.altText.present",
    editable: true,
  },
  {
    id: "colorContrastRatio",
    label: "Color Contrast Ratio",
    type: "number",
    category: "accessibility",
    path: "reviewData.accessibility.data.colorContrast.ratio",
    editable: false,
  },
  {
    id: "colorContrastPasses",
    label: "Contrast Passes WCAG",
    type: "boolean",
    category: "accessibility",
    path: "reviewData.accessibility.data.colorContrast.passes",
    editable: false,
  },
  
  // SEO
  {
    id: "seoScore",
    label: "SEO Score",
    type: "number",
    category: "seo",
    path: "reviewData.seo.data.score",
    editable: false,
    helpText: "Overall SEO optimization score",
  },
  {
    id: "imageFormat",
    label: "Image Format",
    type: "select",
    category: "seo",
    path: "reviewData.seo.data.imageOptimization.format",
    editable: true,
    options: [
      { value: "webp", label: "WebP" },
      { value: "jpg", label: "JPEG" },
      { value: "png", label: "PNG" },
      { value: "svg", label: "SVG" },
      { value: "acceptable", label: "Acceptable" },
    ],
  },
  {
    id: "compressionLevel",
    label: "Compression",
    type: "select",
    category: "seo",
    path: "reviewData.seo.data.imageOptimization.compression",
    editable: true,
    options: [
      { value: "excellent", label: "Excellent" },
      { value: "good", label: "Good" },
      { value: "acceptable", label: "Acceptable" },
      { value: "poor", label: "Poor" },
    ],
  },
  {
    id: "seoSizeRating",
    label: "Size Rating",
    type: "select",
    category: "seo",
    path: "reviewData.seo.data.imageOptimization.sizeRating",
    editable: true,
    options: [
      { value: "excellent", label: "Excellent" },
      { value: "good", label: "Good" },
      { value: "large", label: "Large" },
      { value: "too-large", label: "Too Large" },
    ],
  },
  {
    id: "filenameQuality",
    label: "Filename Quality",
    type: "select",
    category: "seo",
    path: "reviewData.seo.data.metadata.filenameQuality",
    editable: true,
    options: [
      { value: "excellent", label: "Excellent" },
      { value: "good", label: "Good" },
      { value: "fair", label: "Fair" },
      { value: "poor", label: "Poor" },
    ],
  },
  
  // TALENT RIGHTS (NILP)
  {
    id: "creatorIds",
    label: "Talent Credits",
    type: "talent",
    category: "talent",
    path: "creatorIds",
    editable: true,
    helpText: "Assign talent/creators to this asset",
  },
  
  // AI GENERATION
  {
    id: "aiTool",
    label: "AI Tool",
    type: "text",
    category: "ai",
    path: "promptHistory.aiTool",
    editable: true,
    placeholder: "e.g., Midjourney, DALL-E, Stable Diffusion",
  },
  {
    id: "modelVersion",
    label: "Model Version",
    type: "text",
    category: "ai",
    path: "promptHistory.modelVersion",
    editable: true,
    placeholder: "e.g., v6.0, GPT-4",
  },
  {
    id: "prompt",
    label: "Generation Prompt",
    type: "textarea",
    category: "ai",
    path: "promptHistory.messages.0.content",
    editable: true,
    placeholder: "Enter the AI generation prompt",
  },
  {
    id: "generationDate",
    label: "Generation Date",
    type: "date",
    category: "ai",
    path: "promptHistory.generationDate",
    editable: true,
  },
  {
    id: "trainingDataSources",
    label: "Training Data Sources",
    type: "tags",
    category: "ai",
    path: "trainingDataSources",
    editable: true,
    helpText: "Sources used to train the AI model",
  },
  {
    id: "aiModel",
    label: "AI Model",
    type: "text",
    category: "ai",
    path: "aiModel",
    editable: true,
  },
  
  // APPROVAL & STATUS
  {
    id: "approvalStatus",
    label: "Status",
    type: "badge-select",
    category: "approval",
    path: "approvalStatus",
    editable: true,
    versionEditable: true,
    options: [
      { value: "draft", label: "Draft", color: "gray" },
      { value: "submitted", label: "Submitted", color: "blue" },
      { value: "client_review", label: "Client Review", color: "purple" },
      { value: "client_approved", label: "Client OK", color: "green" },
      { value: "admin_review", label: "Admin Review", color: "yellow" },
      { value: "approved", label: "Approved", color: "green" },
      { value: "rejected", label: "Rejected", color: "red" },
    ],
  },
  {
    id: "approvedBy",
    label: "Approved By",
    type: "text",
    category: "approval",
    path: "approvedBy",
    editable: false,
  },
  {
    id: "approvedAt",
    label: "Approval Date",
    type: "date",
    category: "approval",
    path: "approvedAt",
    editable: false,
  },
  {
    id: "qualityScore",
    label: "Quality",
    type: "number",
    category: "approval",
    path: "reviewData.overallScore",
    editable: false,
    helpText: "Overall quality review score (0-100)",
  },
  
  // VERSION MANAGEMENT
  {
    id: "versionStatus",
    label: "Version Status",
    type: "select",
    category: "version",
    path: "status",
    editable: true,
    options: [
      { value: "draft", label: "Draft" },
      { value: "submitted", label: "Submitted" },
      { value: "client_review", label: "Client Review" },
      { value: "client_approved", label: "Client Approved" },
      { value: "admin_review", label: "Admin Review" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
    ],
  },
  {
    id: "versionNumber",
    label: "Version Number",
    type: "number",
    category: "version",
    path: "versionNumber",
    editable: false,
  },
  {
    id: "changeNotes",
    label: "Change Notes",
    type: "textarea",
    category: "version",
    path: "changeNotes",
    editable: true,
    placeholder: "Describe what changed in this version",
  },
  {
    id: "rejectionReason",
    label: "Rejection Reason",
    type: "textarea",
    category: "version",
    path: "rejectionReason",
    editable: true,
  },
  
  // PERFORMANCE
  {
    id: "performanceScore",
    label: "Performance Score",
    type: "number",
    category: "performance",
    path: "reviewData.performance.data.score",
    editable: false,
    helpText: "Overall performance score (0-100)",
  },
  {
    id: "loadTimeEstimate",
    label: "Load Time (ms)",
    type: "number",
    category: "performance",
    path: "reviewData.performance.data.loadTimeEstimate",
    editable: false,
  },
  {
    id: "compressionScore",
    label: "Compression Score",
    type: "number",
    category: "performance",
    path: "reviewData.performance.data.compressionScore",
    editable: false,
  },
  {
    id: "formatRecommendation",
    label: "Format Recommendation",
    type: "text",
    category: "performance",
    path: "reviewData.performance.data.formatRecommendation",
    editable: false,
  },
  
  // SECURITY
  {
    id: "securityScore",
    label: "Security Score",
    type: "number",
    category: "security",
    path: "reviewData.security.data.score",
    editable: false,
    helpText: "Security compliance score (0-100)",
  },
  {
    id: "securitySafe",
    label: "Security Safe",
    type: "boolean",
    category: "security",
    path: "reviewData.security.data.safe",
    editable: false,
  },
  {
    id: "securityThreatsCount",
    label: "Threats Detected",
    type: "number",
    category: "security",
    path: "reviewData.security.data.threats.length",
    editable: false,
  },
  
  // ADDITIONAL METADATA
  {
    id: "ticketId",
    label: "Ticket ID",
    type: "text",
    category: "basic",
    path: "ticketId",
    editable: true,
  },
  {
    id: "ticketTitle",
    label: "Ticket Title",
    type: "text",
    category: "basic",
    path: "ticketTitle",
    editable: true,
  },
  {
    id: "uploadedByName",
    label: "Uploaded By",
    type: "text",
    category: "basic",
    path: "uploadedByName",
    editable: false,
  },
  {
    id: "uploadedAt",
    label: "Upload Date",
    type: "date",
    category: "basic",
    path: "uploadedAt",
    editable: false,
  },
  {
    id: "updatedAt",
    label: "Last Updated",
    type: "date",
    category: "basic",
    path: "updatedAt",
    editable: false,
  },
]

export const getFieldsByCategory = () => {
  return EDITABLE_FIELDS.reduce((acc, field) => {
    if (!acc[field.category]) {
      acc[field.category] = []
    }
    acc[field.category].push(field)
    return acc
  }, {} as Record<string, EditableField[]>)
}

export const getEditableFields = () => EDITABLE_FIELDS.filter(f => f.editable)

export const getFieldById = (id: string) => EDITABLE_FIELDS.find(f => f.id === id)
