/**
 * Mock Prompt Library for Media Manager Development
 * 20 prompts with ratings, usage stats, and varied creative types
 */

export interface PromptLibraryItem {
  id: string
  title: string
  promptText: string
  creativeType: string
  toolUsed: string
  intendedUse: string
  effectivenessRating: number // 1-5 stars
  usageCount: number
  successfulOutputs: number
  tags: string[]
  createdBy: string
  createdDate: Date
  lastUsedDate: Date
  isPrivate: boolean
  category: 'product-photography' | 'social-media' | 'video' | 'copywriting' | 'design' | 'audio'
}

export const MOCK_PROMPT_LIBRARY: PromptLibraryItem[] = [
  {
    id: 'prompt-001',
    title: 'Product Photography - Lifestyle Hero Shot',
    promptText: 'Create a warm, lifestyle product photo showing [product] in a modern kitchen setting. Natural morning light streaming through large windows. Product should be positioned on a marble countertop with minimal, tasteful styling - perhaps a fresh plant and artisan coffee cup nearby. Camera angle: slightly elevated, 45-degree angle. Style: clean, aspirational, not overly staged. Color palette: warm whites, natural wood tones, soft greens. Technical: sharp focus on product, shallow depth of field, 4K resolution.',
    creativeType: 'Product Photography',
    toolUsed: 'Midjourney v6',
    intendedUse: 'Advertising',
    effectivenessRating: 4.5,
    usageCount: 47,
    successfulOutputs: 42,
    tags: ['product-photography', 'midjourney-v6', 'advertising', 'lifestyle'],
    createdBy: 'Sarah Johnson',
    createdDate: new Date('2024-11-15'),
    lastUsedDate: new Date('2025-01-23'),
    isPrivate: false,
    category: 'product-photography'
  },
  {
    id: 'prompt-002',
    title: 'Instagram Carousel - Brand Story',
    promptText: 'Generate a 5-slide Instagram carousel telling our brand origin story. Slide 1: Hook with bold statement about sustainability. Slide 2: Founder\'s journey, authentic moment. Slide 3: Manufacturing process, transparency focus. Slide 4: Impact metrics, community benefit. Slide 5: Call to action with exclusive offer. Style: modern, vibrant brand colors (teal and coral), bold sans-serif typography. Layout: consistent template with photo on left, text on right. Mobile-optimized readability. Include swipe prompt on first slide.',
    creativeType: 'Social Media',
    toolUsed: 'Canva',
    intendedUse: 'Social Media',
    effectivenessRating: 5.0,
    usageCount: 34,
    successfulOutputs: 32,
    tags: ['social-media', 'instagram', 'storytelling', 'carousel', 'brand'],
    createdBy: 'Marcus Chen',
    createdDate: new Date('2024-12-03'),
    lastUsedDate: new Date('2025-01-22'),
    isPrivate: false,
    category: 'social-media'
  },
  {
    id: 'prompt-003',
    title: 'YouTube Thumbnail - High CTR Design',
    promptText: 'Create YouTube thumbnail optimized for maximum click-through rate. Elements: close-up of expressive face (showing surprise/excitement), bold text overlay with 3-5 words in ALL CAPS, high contrast color scheme (bright yellow/red against dark background). Composition: rule of thirds, face on left, text on right. Include subtle arrow or circle highlighting key element. Style: slightly exaggerated contrast, professional but eye-catching. Text must be readable at 320px width. Add thin colored border for feed distinction.',
    creativeType: 'Design',
    toolUsed: 'Photoshop',
    intendedUse: 'Social Media',
    effectivenessRating: 4.8,
    usageCount: 82,
    successfulOutputs: 75,
    tags: ['youtube', 'thumbnail', 'video-marketing', 'high-ctr', 'design'],
    createdBy: 'Aisha Patel',
    createdDate: new Date('2024-11-28'),
    lastUsedDate: new Date('2025-01-24'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-004',
    title: 'Email Subject Line - A/B Test Variants',
    promptText: 'Generate 5 email subject line variants for A/B testing. Product: [product name]. Goal: drive opens and clicks for product launch. Constraints: 50 characters max, mobile-optimized. Include: 1) Curiosity-driven with emoji, 2) Benefit-focused with number, 3) Urgency/scarcity angle, 4) Personalization token, 5) Question format. Avoid spam triggers (FREE, !!!, ALL CAPS). Each should preview well without preheader. Consider inbox psychology - what makes subscriber pause mid-scroll?',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Email',
    effectivenessRating: 4.3,
    usageCount: 56,
    successfulOutputs: 44,
    tags: ['email-marketing', 'copywriting', 'chatgpt', 'subject-lines', 'ab-testing'],
    createdBy: 'David Lee',
    createdDate: new Date('2024-10-18'),
    lastUsedDate: new Date('2025-01-21'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-005',
    title: 'TikTok Hook - First 3 Seconds Script',
    promptText: 'Write compelling first 3 seconds for TikTok video about [topic]. Must: 1) State unexpected fact or contrarian viewpoint, 2) Use pattern interrupt (visual or verbal), 3) Promise valuable payoff. Format: Direct camera address, conversational tone, no fluff. Start with "Did you know..." or "Stop scrolling if..." or "Everyone thinks... but actually...". Hook should create information gap that demands resolution. Include on-screen text suggestion for hearing-impaired accessibility.',
    creativeType: 'Video',
    toolUsed: 'ChatGPT',
    intendedUse: 'Social Media',
    effectivenessRating: 4.6,
    usageCount: 63,
    successfulOutputs: 54,
    tags: ['tiktok', 'video-script', 'social-media', 'short-form', 'hooks'],
    createdBy: 'Emma Rodriguez',
    createdDate: new Date('2024-12-10'),
    lastUsedDate: new Date('2025-01-23'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-006',
    title: 'Podcast Intro Script - 60 Second Open',
    promptText: 'Write 60-second podcast intro script. Structure: 1) Attention-grabbing tease of episode content (15s), 2) Show positioning statement (10s), 3) Host introduction with credibility markers (15s), 4) Episode sponsor mention (15s), 5) Transition to main content (5s). Tone: conversational but professional, energetic without being over-caffeinated. Include: music cue suggestions, pacing notes for editor, emphasis markers for host. Optimize for 1.5x playback speed listeners.',
    creativeType: 'Audio',
    toolUsed: 'ChatGPT',
    intendedUse: 'Editorial',
    effectivenessRating: 4.4,
    usageCount: 29,
    successfulOutputs: 24,
    tags: ['podcast', 'audio', 'script', 'copywriting', 'intro'],
    createdBy: 'James Wilson',
    createdDate: new Date('2024-09-25'),
    lastUsedDate: new Date('2025-01-19'),
    isPrivate: false,
    category: 'audio'
  },
  {
    id: 'prompt-007',
    title: 'Landing Page Hero Section - Above Fold',
    promptText: 'Design above-the-fold hero section for landing page. Elements: 1) Headline addressing core pain point (10 words max), 2) Subheadline expanding on solution (20 words), 3) Primary CTA button (2-3 words action-oriented), 4) Supporting visual or product mockup, 5) Trust indicator (testimonial quote or stat). Layout: F-pattern, focal point top-left for text. Visual: authentic photo, not stock. Include: mobile-responsive notes, accessibility contrast ratio check. Goal: communicate value proposition in 3 seconds.',
    creativeType: 'Design',
    toolUsed: 'Figma',
    intendedUse: 'Web',
    effectivenessRating: 4.7,
    usageCount: 41,
    successfulOutputs: 36,
    tags: ['landing-page', 'web-design', 'hero-section', 'conversion', 'ux'],
    createdBy: 'Olivia Martinez',
    createdDate: new Date('2024-10-05'),
    lastUsedDate: new Date('2025-01-20'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-008',
    title: 'LinkedIn Post - Thought Leadership',
    promptText: 'Write LinkedIn post establishing thought leadership on [topic]. Structure: 1) Personal anecdote or observation (2-3 sentences), 2) Transition to broader industry insight, 3) Data point or trend analysis, 4) Actionable takeaway for readers, 5) Engagement question. Formatting: Short paragraphs, strategic line breaks for mobile. Include emoji as visual anchor (max 2). Tone: professional but personable, no corporate jargon. Aim for 150-200 words. End with open-ended question to drive comments.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Social Media',
    effectivenessRating: 4.2,
    usageCount: 38,
    successfulOutputs: 29,
    tags: ['linkedin', 'social-media', 'thought-leadership', 'copywriting', 'b2b'],
    createdBy: 'Noah Anderson',
    createdDate: new Date('2024-11-12'),
    lastUsedDate: new Date('2025-01-22'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-009',
    title: 'Infographic Data Visualization - Vertical',
    promptText: 'Design vertical infographic (800x2400px) presenting key statistics about [topic]. Structure: intro statement > 4-5 data points > conclusion/CTA. Visual style: icons + charts + short text blocks. Color: brand primary (blue) + 2 complementary (light blue, orange). Layout: clear visual hierarchy, scannable in 10 seconds. Charts: mix of pie, bar, line for variety. Typography: bold headers (24pt), body (16pt), source citations (12pt). Include: data source attribution, brand logo, social share prompt. Export-ready for Instagram/Pinterest.',
    creativeType: 'Design',
    toolUsed: 'Canva',
    intendedUse: 'Social Media',
    effectivenessRating: 4.9,
    usageCount: 52,
    successfulOutputs: 48,
    tags: ['infographic', 'data-viz', 'canva', 'visual-content', 'social-media'],
    createdBy: 'Sophia Taylor',
    createdDate: new Date('2024-12-15'),
    lastUsedDate: new Date('2025-01-24'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-010',
    title: 'Product Demo Video Script - 30 Second',
    promptText: 'Write 30-second product demo video script showing key benefits. Structure: Problem statement (5s) > Solution introduction (8s) > 3 key features with visual demos (12s) > Call to action (5s). Tone: friendly, confident, not salesy. Include: on-screen text cues, b-roll suggestions, transition notes. Pacing: fast but clear. Visual style: modern, clean product shots. End card: clear CTA with promo code. Script should work with or without audio (captions-first approach).',
    creativeType: 'Video',
    toolUsed: 'ChatGPT',
    intendedUse: 'Advertising',
    effectivenessRating: 4.5,
    usageCount: 45,
    successfulOutputs: 40,
    tags: ['video-script', 'product-demo', 'advertising', 'short-form', '30-second'],
    createdBy: 'Liam Brown',
    createdDate: new Date('2024-11-08'),
    lastUsedDate: new Date('2025-01-21'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-011',
    title: 'Product Photography - E-commerce White Background',
    promptText: 'Create professional e-commerce product photos on pure white background (#FFFFFF). Requirements: Product centered, fills 80% of frame, even lighting with no harsh shadows, sharp focus throughout, subtle shadow beneath for depth. Camera: straight-on angle for apparel, 45-degree for hard goods. Post-processing: remove any color cast, pure white background, subtle sharpening. Export: 2000x2000px, sRGB color space, optimized for web. Include: multiple angles, detail shots of key features.',
    creativeType: 'Product Photography',
    toolUsed: 'Midjourney v6',
    intendedUse: 'Web',
    effectivenessRating: 4.8,
    usageCount: 67,
    successfulOutputs: 63,
    tags: ['product-photography', 'ecommerce', 'white-background', 'midjourney-v6', 'web'],
    createdBy: 'Isabella Garcia',
    createdDate: new Date('2024-10-22'),
    lastUsedDate: new Date('2025-01-24'),
    isPrivate: false,
    category: 'product-photography'
  },
  {
    id: 'prompt-012',
    title: 'Blog Post Intro - Hook + SEO',
    promptText: 'Write compelling blog post introduction (150-200 words) for [topic]. Structure: Hook with relatable problem or surprising stat (1 sentence) > Expand on pain point (2-3 sentences) > Hint at solution and article value (2 sentences) > Include primary keyword naturally in first 100 words. Tone: conversational expert, empathetic to reader struggle. Include: rhetorical question, active voice, transitional phrase to main content. Goal: keep reader scrolling, establish credibility, signal SEO relevance.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Editorial',
    effectivenessRating: 4.1,
    usageCount: 33,
    successfulOutputs: 25,
    tags: ['blog', 'seo', 'copywriting', 'content-marketing', 'intro'],
    createdBy: 'Ethan White',
    createdDate: new Date('2024-09-14'),
    lastUsedDate: new Date('2025-01-18'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-013',
    title: 'Social Media Ad Copy - Facebook/Instagram',
    promptText: 'Write high-converting Facebook/Instagram ad copy for [product/service]. Components: Headline (5 words, benefit-driven), Primary text (125 chars, problem>solution), Description link text (action-oriented). Include: 1 emoji for visual break, urgency element (limited time/quantity), clear value proposition, social proof hint. Tone: casual but credible. CTA: strong action verb + benefit. A/B test angle: Include both feature-focused and emotion-focused variants. Mobile-first readability.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Advertising',
    effectivenessRating: 4.6,
    usageCount: 71,
    successfulOutputs: 64,
    tags: ['facebook-ads', 'instagram-ads', 'social-media', 'advertising', 'conversion'],
    createdBy: 'Mia Johnson',
    createdDate: new Date('2024-12-01'),
    lastUsedDate: new Date('2025-01-23'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-014',
    title: 'Brand Guidelines - Color Palette',
    promptText: 'Design comprehensive brand color palette. Structure: Primary color (1), Secondary colors (2-3), Accent colors (2), Neutral colors (gray scale, 5 shades). For each color provide: Hex code, RGB, CMYK values, usage guidelines (when/where to use), accessibility notes (contrast ratios for text). Include: Color psychology rationale, industry context, competitor differentiation. Create: digital palette (screen), print palette (CMYK), accessibility-compliant pairings. Export: style guide format with visual swatches.',
    creativeType: 'Design',
    toolUsed: 'Figma',
    intendedUse: 'Internal',
    effectivenessRating: 4.7,
    usageCount: 18,
    successfulOutputs: 17,
    tags: ['brand-guidelines', 'color-palette', 'design-system', 'figma', 'style-guide'],
    createdBy: 'Alexander Martinez',
    createdDate: new Date('2024-08-30'),
    lastUsedDate: new Date('2025-01-15'),
    isPrivate: true,
    category: 'design'
  },
  {
    id: 'prompt-015',
    title: 'Explainer Video Script - 90 Second',
    promptText: 'Write 90-second animated explainer video script for [product/service]. Structure: Problem setup (20s) > Solution introduction (15s) > How it works - 3 steps (35s) > Benefits summary (15s) > Call to action (5s). Style: Simple language, active voice, conversational. Visual cues: Scene transitions, on-screen text highlights, character actions. Tone: Friendly guide, not corporate pitch. Include: Metaphors for complex concepts, repetition of brand name (3x), memorable closing line. Voiceover-ready with natural pauses.',
    creativeType: 'Video',
    toolUsed: 'ChatGPT',
    intendedUse: 'Web',
    effectivenessRating: 4.9,
    usageCount: 24,
    successfulOutputs: 23,
    tags: ['explainer-video', 'script', 'video-marketing', 'animation', '90-second'],
    createdBy: 'Charlotte Anderson',
    createdDate: new Date('2024-11-25'),
    lastUsedDate: new Date('2025-01-22'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-016',
    title: 'Email Newsletter - Weekly Roundup',
    promptText: 'Write engaging weekly email newsletter. Structure: Personal greeting with editor note (50 words) > Top 3 curated content pieces with titles + 2-sentence summaries + CTA links > Community spotlight (customer story or milestone, 75 words) > Quick tips section (3 actionable bullets) > Upcoming events/announcements > Sign-off with P.S. teaser. Design notes: Mobile-responsive, scannable with headers, emoji section dividers, max 500 words total. Tone: Helpful friend sharing valuable resources, not broadcasting.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Email',
    effectivenessRating: 4.3,
    usageCount: 44,
    successfulOutputs: 36,
    tags: ['email-newsletter', 'content-curation', 'email-marketing', 'engagement'],
    createdBy: 'Benjamin Clark',
    createdDate: new Date('2024-10-12'),
    lastUsedDate: new Date('2025-01-20'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-017',
    title: 'Instagram Reel Script - 15 Second Hook',
    promptText: 'Write script for 15-second Instagram Reel about [topic]. Structure: Visual hook (2s, pattern interrupt) > Core value statement (3s, one clear benefit) > Quick demonstration or proof point (8s, show don\'t tell) > Call to action (2s, follow/save/comment). Format: Scene-by-scene breakdown with on-screen text, transitions, music mood notes. Pacing: Fast cuts, energetic. Include: Trending audio suggestions, caption for sound-off viewers, hook variations for A/B testing. Optimize for loop replays.',
    creativeType: 'Video',
    toolUsed: 'ChatGPT',
    intendedUse: 'Social Media',
    effectivenessRating: 4.7,
    usageCount: 88,
    successfulOutputs: 81,
    tags: ['instagram-reels', 'short-form-video', 'social-media', 'script', '15-second'],
    createdBy: 'Ava Martinez',
    createdDate: new Date('2024-12-18'),
    lastUsedDate: new Date('2025-01-24'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-018',
    title: 'Product Packaging Design - Minimalist',
    promptText: 'Design minimalist product packaging for [product category]. Visual approach: Clean, uncluttered layout with generous white space, single hero image or simple icon, limited color palette (2-3 colors max), sans-serif typography. Required elements: Product name (large, bold), key benefit statement (one line), minimal ingredients/specs list, barcode placement. Sustainability: Recyclable materials note, eco-friendly color choices. Include: Unboxing experience consideration, shelf presence at retail, Instagram-worthy aesthetic. Export: Print-ready files with die-cut lines.',
    creativeType: 'Design',
    toolUsed: 'Adobe Illustrator',
    intendedUse: 'Print',
    effectivenessRating: 4.8,
    usageCount: 31,
    successfulOutputs: 29,
    tags: ['packaging-design', 'minimalist', 'print', 'product-design', 'branding'],
    createdBy: 'Lucas Thompson',
    createdDate: new Date('2024-11-05'),
    lastUsedDate: new Date('2025-01-19'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-019',
    title: 'Podcast Episode Description - SEO Optimized',
    promptText: 'Write SEO-optimized podcast episode description (200-300 words). Structure: Compelling hook question or statement (1 sentence) > Episode topic overview (2-3 sentences) > Key discussion points as bullets (4-6 points) > Guest bio with credentials (2 sentences if applicable) > Actionable takeaway preview (1 sentence) > Timestamps for major sections > Links to resources mentioned > Social handles and hashtags. Keywords: Include target keyword 3-4 times naturally, related terms. Call to action: Subscribe, rate, share. Optimize for podcast platform search and Google.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Editorial',
    effectivenessRating: 4.4,
    usageCount: 37,
    successfulOutputs: 31,
    tags: ['podcast', 'seo', 'show-notes', 'content-marketing', 'audio'],
    createdBy: 'Harper Lewis',
    createdDate: new Date('2024-09-20'),
    lastUsedDate: new Date('2025-01-21'),
    isPrivate: false,
    category: 'audio'
  },
  {
    id: 'prompt-020',
    title: 'Brand Storytelling - Origin Story Post',
    promptText: 'Write authentic brand origin story for social media or About page. Structure: The problem that sparked the idea (personal anecdote, 3-4 sentences) > The "aha moment" or turning point (2-3 sentences) > Early struggles and lessons learned (vulnerability, 3-4 sentences) > Evolution to current mission (2-3 sentences) > Values and what drives the team today (2 sentences) > Forward-looking vision (1 sentence). Tone: Genuine, human, not overly polished. Include: Specific details that build credibility, emotional connection points, subtle brand values integration. Length: 250-350 words.',
    creativeType: 'Copywriting',
    toolUsed: 'ChatGPT',
    intendedUse: 'Social Media',
    effectivenessRating: 4.9,
    usageCount: 42,
    successfulOutputs: 40,
    tags: ['brand-storytelling', 'origin-story', 'about-page', 'copywriting', 'authenticity'],
    createdBy: 'Evelyn Walker',
    createdDate: new Date('2024-12-08'),
    lastUsedDate: new Date('2025-01-23'),
    isPrivate: false,
    category: 'copywriting'
  }
]
