/**
 * Mock Prompt Library for Media Manager Development
 * 20 prompts with ratings, usage stats, and varied creative types
 */

export interface PromptLibraryItem {
  id: string
  title: string
  text: string
  effectivenessRating: number // 1-5 stars
  usageCount: number
  successRate: number // percentage
  tags: string[]
  createdBy: string
  createdAt: Date
  lastUsed: Date
  isPrivate: boolean
  category: 'product-photography' | 'social-media' | 'video' | 'copywriting' | 'design' | 'audio'
}

export const MOCK_PROMPT_LIBRARY: PromptLibraryItem[] = [
  {
    id: 'prompt-001',
    title: 'Product Photography - Lifestyle Hero Shot',
    text: 'Create a warm, lifestyle product photo showing [product] in a modern kitchen setting. Natural morning light streaming through large windows. Product should be positioned on a marble countertop with minimal, tasteful styling - perhaps a fresh plant and artisan coffee cup nearby. Camera angle: slightly elevated, 45-degree angle. Style: clean, aspirational, not overly staged. Color palette: warm whites, natural wood tones, soft greens. Technical: sharp focus on product, shallow depth of field, 4K resolution.',
    effectivenessRating: 4.5,
    usageCount: 47,
    successRate: 89,
    tags: ['product-photography', 'midjourney-v6', 'advertising', 'lifestyle'],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2024-11-15'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'product-photography'
  },
  {
    id: 'prompt-002',
    title: 'Instagram Carousel - Brand Story',
    text: 'Generate a 5-slide Instagram carousel telling our brand origin story. Slide 1: Hook with bold statement about sustainability. Slide 2: Founder\'s journey, authentic moment. Slide 3: Manufacturing process, transparency focus. Slide 4: Impact metrics, community benefit. Slide 5: Call to action with exclusive offer. Style: modern, vibrant brand colors (teal and coral), bold sans-serif typography. Layout: consistent template with photo on left, text on right. Mobile-optimized readability. Include swipe prompt on first slide.',
    effectivenessRating: 5.0,
    usageCount: 34,
    successRate: 94,
    tags: ['social-media', 'instagram', 'storytelling', 'carousel', 'brand'],
    createdBy: 'Marcus Chen',
    createdAt: new Date('2024-12-03'),
    lastUsed: new Date('2025-01-22'),
    isPrivate: false,
    category: 'social-media'
  },
  {
    id: 'prompt-003',
    title: 'YouTube Thumbnail - High CTR Design',
    text: 'Create YouTube thumbnail optimized for maximum click-through rate. Elements: close-up of expressive face (showing surprise/excitement), bold text overlay with 3-5 words in ALL CAPS, high contrast color scheme (bright yellow/red against dark background). Composition: rule of thirds, face on left, text on right. Include subtle arrow or circle highlighting key element. Style: slightly exaggerated contrast, professional but eye-catching. Text must be readable at 320px width. Add thin colored border for feed distinction.',
    effectivenessRating: 4.8,
    usageCount: 82,
    successRate: 91,
    tags: ['youtube', 'thumbnail', 'video-marketing', 'high-ctr', 'design'],
    createdBy: 'Aisha Patel',
    createdAt: new Date('2024-11-28'),
    lastUsed: new Date('2025-01-24'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-004',
    title: 'Email Subject Line - A/B Test Variants',
    text: 'Generate 5 email subject line variants for A/B testing. Product: [product name]. Goal: drive opens and clicks for product launch. Constraints: 50 characters max, mobile-optimized. Include: 1) Curiosity-driven with emoji, 2) Benefit-focused with number, 3) Urgency/scarcity angle, 4) Personalization token, 5) Question format. Avoid spam triggers (FREE, !!!, ALL CAPS). Each should preview well without preheader. Consider inbox psychology - what makes subscriber pause mid-scroll?',
    effectivenessRating: 4.3,
    usageCount: 56,
    successRate: 78,
    tags: ['email-marketing', 'copywriting', 'chatgpt', 'subject-lines', 'ab-testing'],
    createdBy: 'David Lee',
    createdAt: new Date('2024-10-18'),
    lastUsed: new Date('2025-01-21'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-005',
    title: 'TikTok Hook - First 3 Seconds Script',
    text: 'Write compelling first 3 seconds for TikTok video about [topic]. Must: 1) State unexpected fact or contrarian viewpoint, 2) Use pattern interrupt (visual or verbal), 3) Promise valuable payoff. Format: Direct camera address, conversational tone, no fluff. Start with "Did you know..." or "Stop scrolling if..." or "Everyone thinks... but actually...". Hook should create information gap that demands resolution. Include on-screen text suggestion for hearing-impaired accessibility.',
    effectivenessRating: 4.6,
    usageCount: 63,
    successRate: 85,
    tags: ['tiktok', 'video-script', 'social-media', 'short-form', 'hooks'],
    createdBy: 'Emma Rodriguez',
    createdAt: new Date('2024-12-10'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-006',
    title: 'Podcast Intro Script - 60 Second Open',
    text: 'Write 60-second podcast intro script. Structure: 1) Attention-grabbing tease of episode content (15s), 2) Show positioning statement (10s), 3) Host introduction with credibility markers (15s), 4) Episode sponsor mention (15s), 5) Transition to main content (5s). Tone: conversational but professional, energetic without being over-caffeinated. Include: music cue suggestions, pacing notes for editor, emphasis markers for host. Optimize for 1.5x playback speed listeners.',
    effectivenessRating: 4.4,
    usageCount: 29,
    successRate: 82,
    tags: ['podcast', 'audio', 'script', 'copywriting', 'intro'],
    createdBy: 'James Wilson',
    createdAt: new Date('2024-09-25'),
    lastUsed: new Date('2025-01-19'),
    isPrivate: false,
    category: 'audio'
  },
  {
    id: 'prompt-007',
    title: 'Landing Page Hero Section - Above Fold',
    text: 'Design above-the-fold hero section for landing page. Elements: 1) Headline addressing core pain point (10 words max), 2) Subheadline expanding on solution (20 words), 3) Primary CTA button (2-3 words action-oriented), 4) Supporting visual or product mockup, 5) Trust indicator (testimonial quote or stat). Layout: F-pattern, focal point top-left for text. Visual: authentic photo, not stock. Include: mobile-responsive notes, accessibility contrast ratio check. Goal: communicate value proposition in 3 seconds.',
    effectivenessRating: 4.7,
    usageCount: 41,
    successRate: 88,
    tags: ['landing-page', 'web-design', 'hero-section', 'conversion', 'ux'],
    createdBy: 'Olivia Martinez',
    createdAt: new Date('2024-10-05'),
    lastUsed: new Date('2025-01-20'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-008',
    title: 'LinkedIn Post - Thought Leadership',
    text: 'Write LinkedIn post establishing thought leadership on [topic]. Structure: 1) Personal anecdote or observation (2-3 sentences), 2) Transition to broader industry insight, 3) Data point or trend analysis, 4) Actionable takeaway for readers, 5) Engagement question. Formatting: Short paragraphs, strategic line breaks for mobile. Include emoji as visual anchor (max 2). Tone: professional but personable, no corporate jargon. Aim for 150-200 words. End with open-ended question to drive comments.',
    effectivenessRating: 4.2,
    usageCount: 38,
    successRate: 76,
    tags: ['linkedin', 'social-media', 'thought-leadership', 'copywriting', 'b2b'],
    createdBy: 'Noah Anderson',
    createdAt: new Date('2024-11-12'),
    lastUsed: new Date('2025-01-22'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-009',
    title: 'Infographic Data Visualization - Vertical',
    text: 'Design vertical infographic (800x2400px) presenting key statistics about [topic]. Structure: intro statement > 4-5 data points > conclusion/CTA. Visual style: icons + charts + short text blocks. Color: brand primary (blue) + 2 complementary (light blue, orange). Layout: clear visual hierarchy, scannable in 10 seconds. Charts: mix of pie, bar, line for variety. Typography: bold headers (24pt), body (16pt), source citations (12pt). Include: data source attribution, brand logo, social share prompt. Export-ready for Instagram/Pinterest.',
    effectivenessRating: 4.9,
    usageCount: 52,
    successRate: 93,
    tags: ['infographic', 'data-viz', 'design', 'statistics', 'visual-content'],
    createdBy: 'Sophia Taylor',
    createdAt: new Date('2024-12-08'),
    lastUsed: new Date('2025-01-24'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-010',
    title: 'Product Demo Video - 90 Second Script',
    text: 'Write 90-second product demo video script. Act 1 (20s): Establish pain point viewer experiences. Act 2 (40s): Show product solving problem, 3-4 key features with visual demonstrations. Act 3 (20s): Results/benefits, social proof, CTA. Act 4 (10s): Pricing/offer, final CTA. Voiceover: conversational, second-person ("you"), benefit-focused not feature-focused. Include: B-roll suggestions, on-screen text callouts, music mood, pacing notes. Optimize for social media (subtitles required).',
    effectivenessRating: 4.5,
    usageCount: 44,
    successRate: 84,
    tags: ['video-script', 'product-demo', 'marketing', 'sales', 'explainer'],
    createdBy: 'Liam Thompson',
    createdAt: new Date('2024-11-20'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-011',
    title: 'Blog Article - SEO Optimized Intro',
    text: 'Write SEO-optimized blog article introduction for keyword: [keyword]. First paragraph: Hook with surprising stat or common misconception. Second paragraph: Promise what article will cover, include primary keyword naturally. Third paragraph: Establish credibility, preview key takeaways. Length: 150-200 words total. Keyword density: 2-3%. Include: related keywords, semantic variations. Tone: helpful expert, accessible not academic. Structure: short sentences, readable Flesch score 60+. Add internal link opportunity. Goal: reduce bounce rate, encourage scrolling.',
    effectivenessRating: 4.1,
    usageCount: 67,
    successRate: 74,
    tags: ['blog', 'seo', 'content-marketing', 'copywriting', 'keyword-optimization'],
    createdBy: 'Isabella Garcia',
    createdAt: new Date('2024-09-15'),
    lastUsed: new Date('2025-01-21'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-012',
    title: 'Brand Guidelines - Logo Usage Rules',
    text: 'Design brand guidelines page for logo usage. Sections: 1) Primary logo (full color, lockup), 2) Logo variations (horizontal, vertical, icon only), 3) Clear space requirements (diagram showing minimum padding), 4) Minimum size specifications, 5) Color variations (on white, on black, single color), 6) Don\'ts section (stretched, recolored, outlined examples). Include: downloadable assets button, measurement specifications, HEX/RGB/CMYK values. Layout: clean, professional, easy to reference. Export: print-ready PDF and web-optimized version.',
    effectivenessRating: 4.6,
    usageCount: 23,
    successRate: 91,
    tags: ['brand-guidelines', 'logo', 'design-system', 'documentation', 'branding'],
    createdBy: 'Ethan Brown',
    createdAt: new Date('2024-08-20'),
    lastUsed: new Date('2025-01-18'),
    isPrivate: true,
    category: 'design'
  },
  {
    id: 'prompt-013',
    title: 'Customer Testimonial - Video Interview Questions',
    text: 'Generate 8 customer testimonial video interview questions. Flow: warm-up > problem/solution > results > emotion. Questions: 1) Describe situation before product, 2) What made you choose us?, 3) Walk through implementation, 4) Specific results achieved (numbers), 5) Unexpected benefits?, 6) How has it changed your [work/life]?, 7) What would you tell someone considering?, 8) Rating 1-10, why that number?. Phrasing: open-ended, encourages storytelling not yes/no. Include: follow-up prompt suggestions, interviewer notes for authentic responses.',
    effectivenessRating: 4.4,
    usageCount: 31,
    successRate: 83,
    tags: ['testimonial', 'video', 'customer-story', 'case-study', 'interview'],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2024-10-28'),
    lastUsed: new Date('2025-01-22'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-014',
    title: 'Event Invitation - Email HTML Design',
    text: 'Design email invitation for [event type]. Header: event name + compelling visual. Body sections: 1) What (1-2 sentence description), 2) When (date/time prominent, add-to-calendar button), 3) Where (address + map embed/link), 4) Why attend (3-4 bullet benefits), 5) Agenda preview, 6) Speakers/special guests with headshots. Footer: dress code, parking info, contact. CTA: primary "Register Now" button (3+ instances). Mobile-responsive, 600px width max. Include: social sharing buttons, forward-to-friend option. Test: subject line, preheader, spam score.',
    effectivenessRating: 4.3,
    usageCount: 27,
    successRate: 80,
    tags: ['email', 'event', 'invitation', 'design', 'marketing'],
    createdBy: 'Marcus Chen',
    createdAt: new Date('2024-09-08'),
    lastUsed: new Date('2025-01-19'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-015',
    title: 'Social Media Calendar - Monthly Template',
    text: 'Create monthly social media content calendar template for [brand]. Content mix: 40% educational, 30% promotional, 20% user-generated content, 10% behind-scenes. Post frequency: Instagram 5x/week, LinkedIn 3x/week, TikTok 4x/week. Include: campaign themes, key dates/holidays, content pillars, hashtag strategy. Format: spreadsheet with columns for date, platform, content type, copy, visual description, link, CTA, tracking tags. Color-code: campaigns, content types. Add: approval workflow, asset needs, performance benchmarks.',
    effectivenessRating: 4.0,
    usageCount: 39,
    successRate: 72,
    tags: ['social-media', 'content-calendar', 'planning', 'strategy', 'organization'],
    createdBy: 'Aisha Patel',
    createdAt: new Date('2024-11-01'),
    lastUsed: new Date('2025-01-20'),
    isPrivate: true,
    category: 'social-media'
  },
  {
    id: 'prompt-016',
    title: 'Product Launch - Press Release',
    text: 'Write press release for product launch. Structure: Headline (compelling, keyword-rich, 10 words). Dateline: [CITY, STATE] - [DATE]. Lead paragraph: who, what, when, where, why (5 Ws). Body: 1) Product problem/solution, 2) Key features/benefits, 3) Target market, 4) Availability/pricing, 5) Company background, 6) Future plans. Include: executive quote (inspirational), customer quote (validating). Boilerplate: company description. Contact info: PR contact name/email/phone. Length: 400-600 words. Tone: newsworthy not salesy. AP style formatting.',
    effectivenessRating: 4.2,
    usageCount: 18,
    successRate: 78,
    tags: ['press-release', 'pr', 'product-launch', 'copywriting', 'media'],
    createdBy: 'David Lee',
    createdAt: new Date('2024-10-12'),
    lastUsed: new Date('2025-01-17'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-017',
    title: 'Motion Graphics - Logo Animation',
    text: 'Create 3-5 second logo reveal animation for video intros. Style: smooth, professional, subtle not distracting. Motion: logo builds in (fade + scale OR draw on effect), holds 1.5s, subtle float/breathe. Audio: clean whoosh or chime (optional). Background: transparent OR brand gradient. Timing: ease-in/ease-out curves, no hard cuts. Export: 4K resolution, multiple formats (MP4, MOV with alpha channel, GIF). Variations: light theme, dark theme, social media square version. Mood: premium, polished, on-brand.',
    effectivenessRating: 4.7,
    usageCount: 33,
    successRate: 89,
    tags: ['motion-graphics', 'animation', 'logo', 'video-production', 'after-effects'],
    createdBy: 'Emma Rodriguez',
    createdAt: new Date('2024-11-18'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-018',
    title: 'User Onboarding - Welcome Email Sequence',
    text: 'Design 3-email welcome sequence for new users. Email 1 (immediate): Thank you, set expectations, quick start guide, first action to take. Email 2 (day 2): Feature spotlight, use case example, helpful resources, support contact. Email 3 (day 5): Success story/testimonial, advanced tips, community invite, feedback request. Each email: conversational tone, single clear CTA, mobile-optimized. Subject lines: curiosity-driven. Include: unsubscribe option, preference center. Metrics: track opens, clicks, feature adoption. A/B test: send time, subject line, CTA copy.',
    effectivenessRating: 4.6,
    usageCount: 49,
    successRate: 87,
    tags: ['email-sequence', 'onboarding', 'automation', 'user-experience', 'retention'],
    createdBy: 'James Wilson',
    createdAt: new Date('2024-12-15'),
    lastUsed: new Date('2025-01-24'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-019',
    title: 'Podcast Cover Art - Apple Podcasts Spec',
    text: 'Design podcast cover art (3000x3000px, RGB, 72dpi). Requirements: 1) Show title bold and legible at thumbnail size (256x256), 2) Host name/photo (if personality-driven show), 3) Visual theme element representing content, 4) Brand colors, professional polish. Typography: san-serif, high contrast, no thin fonts. Test: legibility in Apple Podcasts app, dark mode, car display. Avoid: busy backgrounds, small text, too many elements. Include: square version, rectangular banner (3000x1000 for Spotify). Export: JPG 80% quality, max 512kb file size.',
    effectivenessRating: 4.3,
    usageCount: 21,
    successRate: 81,
    tags: ['podcast', 'cover-art', 'design', 'branding', 'apple-podcasts'],
    createdBy: 'Olivia Martinez',
    createdAt: new Date('2024-08-30'),
    lastUsed: new Date('2025-01-16'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-020',
    title: 'UGC Campaign - Content Creator Brief',
    text: 'Write creator brief for user-generated content campaign. Sections: 1) Campaign overview (goal, timeline, deliverables), 2) Brand voice/values, 3) Content requirements (format, length, must-include elements), 4) Creative direction (mood, tone, examples), 5) Dos and don\'ts (brand guidelines, legal), 6) Submission process, 7) Compensation/usage rights, 8) Key dates/deadlines. Tone: collaborative, clear, inspiring. Include: shot list suggestions, hashtags, disclosure requirements, examples of great UGC. Goal: authentic content that feels native, not ad-like.',
    effectivenessRating: 4.5,
    usageCount: 36,
    successRate: 86,
    tags: ['ugc', 'campaign', 'content-creation', 'creator-brief', 'influencer-marketing'],
    createdBy: 'Noah Anderson',
    createdAt: new Date('2024-12-22'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-011',
    title: 'Testimonial Quote Card - Social Media Graphic',
    text: 'Design testimonial quote graphic for Instagram. Layout: centered quote text (20-30 words max), customer name/title below, 5-star rating visual, subtle brand watermark. Style: elegant, minimal, trustworthy. Background: soft gradient or solid brand color. Typography: serif for quote (emotional), sans-serif for attribution. Include: quotation marks prominent, customer photo optional. Dimensions: 1080x1080. Color: maintains brand palette while feeling authentic not overly promotional. Export: web-optimized PNG.',
    effectivenessRating: 4.8,
    usageCount: 59,
    successRate: 92,
    tags: ['testimonial', 'social-media', 'quote', 'instagram', 'social-proof'],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2024-10-15'),
    lastUsed: new Date('2025-01-24'),
    isPrivate: false,
    category: 'social-media'
  },
  {
    id: 'prompt-012',
    title: 'Animated Explainer Video - Storyboard',
    text: 'Create storyboard for 60-second animated explainer video. Scene 1 (10s): Establish problem with relatable character. Scene 2 (15s): Introduce product as solution, key benefit. Scene 3 (20s): Show product features via animated sequence. Scene 4 (10s): Results/transformation of character. Scene 5 (5s): CTA and brand logo. Style: flat design, friendly characters, smooth transitions. Color: brand colors with pops of accent. Include: scene descriptions, voiceover notes, animation style references. Frame dimensions: 1920x1080 for YouTube.',
    effectivenessRating: 4.6,
    usageCount: 26,
    successRate: 88,
    tags: ['explainer-video', 'animation', 'storyboard', 'video-production', 'storytelling'],
    createdBy: 'Marcus Chen',
    createdAt: new Date('2024-09-22'),
    lastUsed: new Date('2025-01-19'),
    isPrivate: false,
    category: 'video'
  },
  {
    id: 'prompt-013',
    title: 'FAQ Page - Conversion-Optimized Layout',
    text: 'Design FAQ page optimized for conversion and SEO. Structure: Hero section with search bar > Category tabs (Product, Billing, Shipping, Returns, Technical) > Accordion-style Q&As. Each Q&A: Question as H3 (keyword-rich), answer in plain language (100-150 words), CTA where relevant, related articles links. Include: "Still have questions?" contact section, chatbot trigger, PDF download option. Design: scannable, mobile-friendly, generous whitespace. Add: structured data markup, search functionality, most-viewed tracking.',
    effectivenessRating: 4.4,
    usageCount: 33,
    successRate: 81,
    tags: ['faq', 'customer-service', 'web-design', 'seo', 'conversion'],
    createdBy: 'Aisha Patel',
    createdAt: new Date('2024-11-05'),
    lastUsed: new Date('2025-01-20'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-014',
    title: 'Behind-the-Scenes Content - Instagram Stories',
    text: 'Plan 5-slide Instagram Story showing behind-the-scenes of [process]. Slide 1: Hook text "Ever wonder how we...?". Slide 2: Setup/preparation shot, text overlay explaining. Slide 3-4: Process in action, engaging moments, team members. Slide 5: Final result + poll/question sticker. Style: authentic, unpolished in a polished way, candid moments. Text: casual, conversational, emoji accents. Music: upbeat but not distracting. Include: sticker suggestions (poll, question, countdown), swipe-up CTA if available. Goal: humanize brand, build connection.',
    effectivenessRating: 4.7,
    usageCount: 48,
    successRate: 90,
    tags: ['instagram', 'stories', 'bts', 'social-media', 'authentic-content'],
    createdBy: 'David Lee',
    createdAt: new Date('2024-12-01'),
    lastUsed: new Date('2025-01-23'),
    isPrivate: false,
    category: 'social-media'
  },
  {
    id: 'prompt-015',
    title: 'White Paper - Executive Summary Page',
    text: 'Write executive summary page for white paper. Length: 1 page max (400 words). Structure: 1) Opening statement of core finding/thesis, 2) Context/problem landscape, 3) Key insights (3-4 numbered points), 4) Methodology brief, 5) Implications/recommendations, 6) Next steps/CTA. Tone: authoritative but accessible, data-driven, thought leadership positioning. Include: compelling statistics, industry context, credibility markers. Design notes: pull quotes, data callouts, professional layout. Goal: convince reader to download full report.',
    effectivenessRating: 4.2,
    usageCount: 14,
    successRate: 79,
    tags: ['white-paper', 'b2b', 'thought-leadership', 'executive-summary', 'copywriting'],
    createdBy: 'Emma Rodriguez',
    createdAt: new Date('2024-08-12'),
    lastUsed: new Date('2025-01-15'),
    isPrivate: true,
    category: 'copywriting'
  },
  {
    id: 'prompt-016',
    title: 'Product Comparison Chart - Visual Design',
    text: 'Design product comparison chart (us vs. competitor A vs. competitor B). Layout: 3-column table, features in rows. Highlight: our advantages with checkmarks and subtle color, competitors with X or minus. Include: pricing row, feature details, CTA button at bottom of our column. Style: clean, professional, not overly salesy. Typography: clear headers, readable body text. Visual: use icons for features, color-coding for tiers. Add: "Why choose us?" section below chart. Mobile: stack columns, prioritize our product. Export: web + PDF versions.',
    effectivenessRating: 4.5,
    usageCount: 37,
    successRate: 84,
    tags: ['comparison-chart', 'product-marketing', 'design', 'competitive', 'sales-tool'],
    createdBy: 'James Wilson',
    createdAt: new Date('2024-11-08'),
    lastUsed: new Date('2025-01-21'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-017',
    title: 'Webinar Promotion - Multi-Channel Campaign',
    text: 'Create webinar promotion assets for multi-channel campaign. Deliverables: 1) Email invitation (subject + preview + body), 2) LinkedIn post with registration link, 3) Instagram Story teaser, 4) Website banner ad (728x90, 300x250), 5) Reminder email (day before). Key info: topic, date/time, speaker credentials, key takeaways. Tone: professional + valuable (not salesy). Include: urgency elements (limited spots, exclusive content), social proof (previous attendance), FOMO triggers. All assets: consistent branding, clear CTAs, timezone considerations.',
    effectivenessRating: 4.3,
    usageCount: 22,
    successRate: 77,
    tags: ['webinar', 'promotion', 'multi-channel', 'campaign', 'event-marketing'],
    createdBy: 'Olivia Martinez',
    createdAt: new Date('2024-09-30'),
    lastUsed: new Date('2025-01-18'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-018',
    title: 'Minimalist Logo Design - Brand Identity',
    text: 'Design minimalist logo concept for [brand name]. Requirements: 1) Scalable vector, works at 16px and 1000px, 2) Effective in monochrome (one-color), 3) Memorable silhouette, 4) Geometric shapes or abstract letterform. Avoid: gradients, fine details, text-heavy designs, trends that date quickly. Process: sketch 10 concepts, refine top 3, present in context (business card, website, app icon). Include: color versions, black/white, horizontal/vertical layouts. Style: timeless, sophisticated, versatile. Deliverable: AI file with all variations.',
    effectivenessRating: 4.7,
    usageCount: 19,
    successRate: 89,
    tags: ['logo-design', 'branding', 'minimalist', 'identity', 'graphic-design'],
    createdBy: 'Noah Anderson',
    createdAt: new Date('2024-08-05'),
    lastUsed: new Date('2025-01-16'),
    isPrivate: false,
    category: 'design'
  },
  {
    id: 'prompt-019',
    title: 'Case Study - Customer Success Story',
    text: 'Write customer success case study. Structure: 1) Customer intro (company, industry, size), 2) Challenge section (what problem faced), 3) Solution (why chose us, implementation), 4) Results (specific metrics, before/after), 5) Quote (emotional impact), 6) Looking forward (future plans). Length: 800-1200 words. Tone: storytelling, data-backed, inspiring not boastful. Include: pull quotes, stat callouts, customer logo, industry context. Design: scannable with headers, sidebars, imagery. CTA: "See how we can help you" with demo link. SEO: optimize for industry + solution keywords.',
    effectivenessRating: 4.5,
    usageCount: 31,
    successRate: 86,
    tags: ['case-study', 'customer-story', 'testimonial', 'b2b', 'content-marketing'],
    createdBy: 'Sophia Taylor',
    createdAt: new Date('2024-10-20'),
    lastUsed: new Date('2025-01-22'),
    isPrivate: false,
    category: 'copywriting'
  },
  {
    id: 'prompt-020',
    title: 'Interactive Quiz - Lead Generation Tool',
    text: 'Design interactive quiz for lead generation. Structure: 1) Enticing title/intro ("Discover your [X] in 2 minutes"), 2) 5-7 questions (mix multiple choice, slider, image selection), 3) Progress bar, 4) Email gate before results (value exchange), 5) Personalized results page with product recommendations. Questions: engaging, reveal preferences/pain points, not too sales-y. Results: specific insights, actionable advice, soft product pitch. Design: mobile-first, fun micro-interactions, brand colors. Include: social share buttons, retake option, sales team notification on completion.',
    effectivenessRating: 4.9,
    usageCount: 42,
    successRate: 93,
    tags: ['interactive', 'quiz', 'lead-generation', 'engagement', 'conversion'],
    createdBy: 'Liam Thompson',
    createdAt: new Date('2024-12-05'),
    lastUsed: new Date('2025-01-24'),
    isPrivate: false,
    category: 'design'
  }
]
